STLLoader: Buffer Geometry for ASCII files
mrdoob/three.js pull request #10055
Opened 2016-11-07 21:47 UTC by Mugen87

This PR adds support for `BufferGeometry` and ASCII encodes STL files. Besides, it removes the unnecessary `DataView` polyfill in `STLLoader`. The corresponding example `webgl_loader_stl` works without any adjustments.

2016-11-08 23:55 UTC, mrdoob requested changes

2016-11-08 23:55 UTC, mrdoob commented on examples/js/loaders/STLLoader.js
> -		geometry.addAttribute( 'position', new THREE.BufferAttribute( vertices, 3 ) );
Hmm, I would keep the `new` on these.

2016-11-09 09:08 UTC, Mugen87 commented on examples/js/loaders/STLLoader.js
> -		geometry.addAttribute( 'position', new THREE.BufferAttribute( vertices, 3 ) );
`THREE.Float32Attribute` is just a shortcut for `new BufferAttribute( new Float32Array( array ), itemSize );`. I've used this style in most `BufferGeometry` related code. Still change?

2016-11-09 22:28 UTC, mrdoob commented on examples/js/loaders/STLLoader.js
> -		geometry.addAttribute( 'position', new THREE.BufferAttribute( vertices, 3 ) );
Hmm, I'm thinking I should deprecate those... I don't think it was a good idea.

2016-11-09 22:30 UTC, mrdoob commented on examples/js/loaders/STLLoader.js
> -		geometry.addAttribute( 'position', new THREE.BufferAttribute( vertices, 3 ) );
Or, if we're keeping them, we should make them look like the rest of the API by doing...

```js
function Float32Attribute( array, itemSize ) {

	return new BufferAttribute( new Float32Array( array ), itemSize );

}

Float32Attribute.prototype = InstancedBufferAttribute.prototype = Object.create( BufferAttribute.prototype );
Float32Attribute.prototype.constructor = Float32Attribute;
```

2016-11-09 22:37 UTC, mrdoob commented on examples/js/loaders/STLLoader.js
> -		geometry.addAttribute( 'position', new THREE.BufferAttribute( vertices, 3 ) );
I just find it weird that we have `Float32Attribute` (or `Float32BufferAttribute`) and `InstancedBufferAttribute` at the same time. There is something wrong in the API design there.

It's likely that `InstancedBufferAttribute` is the bad one here.

2016-11-09 23:04 UTC, Mugen87 commented on examples/js/loaders/STLLoader.js
> -		geometry.addAttribute( 'position', new THREE.BufferAttribute( vertices, 3 ) );
I see what you mean. We should definitely invest some time for refactoring in order to remove these inconsistencies. For this PR, i will replace the `THREE.Float32Attribute` statements with more explicit code.

I think i like the `THREE.Float32BufferAttribute` approach. We should pursue this idea in an additional PR.

2016-11-09 23:21 UTC, mrdoob approved these changes

2016-11-09 23:21 UTC, merged

2016-11-09 23:21 UTC, mrdoob commented
Thanks!