Adding PolarGridHelper and associated files
mrdoob/three.js pull request #10179
Opened 2016-11-20 16:29 UTC by Hectate

Adding a PolarGridHelper and associated documentation an an update to example 'webgl_helpers'. From issue #10146 with major credit to @Mugen87 for nearly all of the 'real' code, as well as @mrdoob . Thanks to @TristanVALCKE for sparking the discussion.

2016-11-20 16:52 UTC, Mugen87 requested changes

2016-11-20 16:52 UTC, Mugen87 commented on src/extras/helpers/PolarGridHelper.js
> +    color1 = new THREE.Color( color1 !== undefined ? color1 : 0x444444 );
@Hectate Can you please remove all references to the `THREE` namespace. The dependencies should be resolved by the import statements at the top...

2016-11-20 16:52 UTC, Mugen87 commented on src/extras/helpers/PolarGridHelper.js
> +    geometry.addAttribute( 'position', new THREE.Float32Attribute( vertices, 3 ) );
We should also change `Float32Attribute` to the newer `Float32BufferAttribute`.

2016-11-20 16:52 UTC, Mugen87 commented on src/extras/helpers/PolarGridHelper.js
> +import { _Math as Math } from '../../math/Math';
I don't think we need the `_Math` reference here...

2016-11-20 17:04 UTC, Hectate commented on src/extras/helpers/PolarGridHelper.js
> +import { _Math as Math } from '../../math/Math';
We use Math.sin and Math.cos, do you mean we don't need to do `_Math as Math` and just import `Math`?

2016-11-20 17:04 UTC, Hectate commented on src/extras/helpers/PolarGridHelper.js
> +    color1 = new THREE.Color( color1 !== undefined ? color1 : 0x444444 );
Yep, completely slipped my mind. Will fix.

2016-11-20 17:04 UTC, Hectate commented on src/extras/helpers/PolarGridHelper.js
> +    geometry.addAttribute( 'position', new THREE.Float32Attribute( vertices, 3 ) );
Can do.

2016-11-20 17:06 UTC, Hectate commented on src/extras/helpers/PolarGridHelper.js
> +import { _Math as Math } from '../../math/Math';
I just looked at some other source and see that it's not there but Math... works anyway. Not sure where I picked that up from but I'll remove it. 👍

2016-11-20 17:20 UTC, Mugen87 commented on src/extras/helpers/PolarGridHelper.js
> +import { _Math as Math } from '../../math/Math';
`_Math` was the reference to `three.js` internal math lib. In `PolarGridHelper` we just use the plain `Math` object of JavaScript (see http://www.w3schools.com/js/js_math.asp)

2016-11-20 17:24 UTC, Hectate commented on src/extras/helpers/PolarGridHelper.js
> +import { _Math as Math } from '../../math/Math';
Oh duh. Yeah that makes sense :)

2016-11-20 17:29 UTC, Hectate commented
I believe this is ready now.

2016-11-20 17:46 UTC, WestLangley commented on src/extras/helpers/PolarGridHelper.js
> +    divisions = divisions || 50;
I think 64 default divisions is visually more appealing.

2016-11-20 17:48 UTC, WestLangley commented on docs/api/extras/helpers/PolarGridHelper.html
> +		radius -- The radius of the polar grid. This can be any positive number. <br />
Default is ...

2016-11-20 17:50 UTC, Hectate commented on docs/api/extras/helpers/PolarGridHelper.html
> +		radius -- The radius of the polar grid. This can be any positive number. <br />
I cribbed from GridHelper.html, but sure there's no reason we can't be _more_ informative since we're touching it :)

2016-11-20 17:50 UTC, Hectate commented on src/extras/helpers/PolarGridHelper.js
> +export { PolarGridHelper };
👍

2016-11-20 17:53 UTC, WestLangley commented on docs/api/extras/helpers/PolarGridHelper.html
> +		radius -- The radius of the polar grid. This can be any positive number. <br />
You're doing a great job. Why not fix them both. :-)

2016-11-20 18:07 UTC, Hectate commented on src/extras/helpers/PolarGridHelper.js
> +export { PolarGridHelper };
Should be good now, I believe.

2016-11-20 20:12 UTC, TristanVALCKE commented
Did you lint the source accordingly to new eslint implementation ?

2016-11-20 20:48 UTC, Hectate commented
No, I didn't do any linting.

2016-11-21 10:53 UTC, Mugen87 commented
I think we can still merge this PR...

2016-11-23 00:22 UTC, merged

2016-11-23 00:22 UTC, mrdoob commented
Thanks!