Add Clock support in node
mrdoob/three.js pull request #10732
Opened 2017-02-05 12:01 UTC by sasha240100

This pull request is based on issue #8112 
Current usage of `( performance || Date ).now()` breaks node.js with the following error:
```
ReferenceError: performance is not defined
```
I suggest the use of `( typeof performance === 'undefined' ? Date : performance ).now()`. It works in node.js environment as expected.

2017-02-05 12:30 UTC, Mugen87 requested changes

2017-02-05 12:30 UTC, Mugen87 commented on src/core/Clock.js
> +		this.startTime = ( typeof performance === 'undefined' ? Date : performance ).now();
Can you please add a comment in this line? Something like // see #10732

2017-02-05 12:34 UTC, sasha240100 commented on src/core/Clock.js
> +		this.startTime = ( typeof performance === 'undefined' ? Date : performance ).now();
@Mugen87 Will do now

2017-02-05 12:38 UTC, sasha240100 commented on src/core/Clock.js
> +		this.startTime = ( typeof performance === 'undefined' ? Date : performance ).now();
@Mugen87 Done

2017-02-05 12:40 UTC, Mugen87 commented
I don't now why, but the format of the comment looks strange. Maybe like this? 😉 
```javascript

this.startTime = ( typeof performance === 'undefined' ? Date : performance ).now(); // see #10732
```

2017-02-05 12:42 UTC, sasha240100 commented
@Mugen87 I added this one first, then looked to other comments to follow your code style and moved to line before, lol. Will update that again now

2017-02-05 12:44 UTC, sasha240100 commented
@Mugen87 I reimplemented that commit. See now

2017-02-05 16:09 UTC, sasha240100 commented
@mrdoob @Mugen87 Anything else?

2017-02-05 17:18 UTC, Mugen87 commented
Looks good!

2017-02-10 20:06 UTC, sasha240100 commented
@Mugen87 @mrdoob Will it be merged?

2017-02-17 06:41 UTC, sasha240100 commented
@Mugen87 @mrdoob is it still of current interest?

2017-02-17 06:41 UTC, sasha240100 commented
Or should i close it?

2017-02-17 14:21 UTC, Mugen87 commented
It's still a valid PR but I'm unable to merge. Let's wait what @mrdoob says...

2017-02-17 23:28 UTC, mrdoob commented
Looks good indeed! (Sorry for the delay!)

2017-02-17 23:28 UTC, merged

2017-02-17 23:28 UTC, mrdoob commented
Thanks!