Update Cloth.js
mrdoob/three.js pull request #11130
Opened 2017-04-05 03:34 UTC by mghoffmann

I fixed a typo in a function name ("satisfy" instead of "satisify") and removed an assignment that seems unnecessary- I can't find any references to the value of the assigned variable after the assignment.

2017-04-05 04:37 UTC, WestLangley commented
>and removed an assignment that seems unnecessary

Did you test this change?

2017-04-19 19:02 UTC, Mugen87 requested changes

2017-04-19 19:02 UTC, Mugen87 commented on examples/js/Cloth.js
> -	this.tmp = this.previous;
If you undo this change, we can merge the PR and at least fix the typo.

2017-04-19 21:21 UTC, mrdoob commented
I'll merge and clean up if needed.

2017-04-19 21:21 UTC, merged

2017-04-19 21:21 UTC, mrdoob commented
Thanks!

2017-04-19 21:24 UTC, mrdoob commented
Haha!

![screen shot 2017-04-19 at 14 23 33](https://cloud.githubusercontent.com/assets/97088/25202862/d30c634e-250b-11e7-8839-a53ca720dce5.png)

2017-04-19 21:28 UTC, WestLangley commented
Clearly -- a PR not tested.

2017-04-19 21:29 UTC, mrdoob commented
Fixed.

2017-04-22 20:19 UTC, mghoffmann commented
My bad. I searched the code for all references of this.tmp, and it seemed
like it was never used. I guess it was. A more meaningful name might be
good?

Is there some set procedure for testing code changes for this project, so I
don't mess it up again? I hope to contribute what little I can to this.

On Wed, Apr 19, 2017 at 3:29 PM, Mr.doob <notifications@github.com> wrote:

> Fixed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrdoob/three.js/pull/11130#issuecomment-295451305>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJ-Mg70OLGl6wgvki9mCdL9v4atZqaKmks5rxnzUgaJpZM4MztTm>
> .
>

2017-04-22 23:53 UTC, mrdoob commented
> Is there some set procedure for testing code changes for this project, so I
don't mess it up again?

Loading the example in the browser is a good start 😉