Allow Box3 as input for BoxHelper (reimplemtation of pull #8609)
mrdoob/three.js pull request #11207
Opened 2017-04-21 09:55 UTC by ArjanSchouten

Hi,

In this [PR](https://github.com/mrdoob/three.js/pull/8609) the option was added to `BoxHelper` to accept a `Box3` instance. Due to some refactoring it is removed in this commit: https://github.com/mrdoob/three.js/commit/745e567fd3166151c1e8f878462b15746c2dc6bf .

My usecase is that I want to resize the Box3. I want the BoxHelper to update to the Box3 size accordingly.

2017-04-21 11:42 UTC, Mugen87 commented
I was not 100% sure when i removed this code with #11171. It seemed some kind of hacky to me. Code is more consistent if it only regards 3D objects with a geometry.

If we really go back to the old version, we have to correct the [docs](https://threejs.org/docs/index.html#api/helpers/BoxHelper). The support of `Box3` as a compatible parameter was never noted.

2017-04-21 11:59 UTC, ArjanSchouten commented
@Mugen87 yes. If this gets merged than the docs needs to be updated. I was hesitating to commit a doc change with this PR. I first wanted to see if is going to be merged.

2017-04-21 12:00 UTC, Mugen87 commented
Okay, let's see what others say to this change. 👍

2017-04-21 12:04 UTC, Mugen87 requested changes

2017-04-21 12:04 UTC, Mugen87 commented on src/helpers/BoxHelper.js
> +		if ( this.object instanceof Box3 ) {
BTW: We now use the `is*` properties like `isBox3` to determine the type. See https://github.com/mrdoob/three.js/blob/dev/src/math/Box3.js#L18

2017-04-21 12:05 UTC, Mugen87 commented on src/helpers/BoxHelper.js
> +		if ( this.object instanceof Box3 ) {
https://github.com/mrdoob/three.js/blob/c72b7dcc8e5cd6ac2bb19a9605ad6a4171ce42f7/src/helpers/BoxHelper.js#L41

2017-04-21 15:54 UTC, mrdoob commented
Maybe, for clarity, we could do a `Box3Helper`?

2017-04-21 16:02 UTC, WestLangley commented
For reference: existing helpers
```
ArrowHelper( dir, origin, length, color, headLength, headWidth )

VertexNormalsHelper( object, size, hex, linewidth )

BoxHelper( object, color )

DirectionalLightHelper( light, size )

SpotLightHelper( light )

PointLightHelper( light, sphereSize )

GridHelper( size, divisions, color1, color2 )

RectAreaLightHelper( light )

AxisHelper( size )
```

Possible math helpers
```
RayHelper( ray, size, color, length ) // not needed; use ArrowHelper 

SphereHelper( sphere, color, widthSegments, heightSegments ) // not needed; use Sphere mesh

TriangleHelper( triangle, color ) // probably not needed

PlaneHelper( plane, color, width, height ) // implement similarly to DirectionalLightHelper

Box3Helper( box3, color ) // similar to BoxHelper
```

I would suggest implementing the last two.

2017-04-21 16:24 UTC, Mugen87 commented
I like the idea of a `Box3Helper`. `PlaneHelper` sound also useful to me.

2017-04-21 16:59 UTC, WestLangley commented
On the other hand, why not just this?
```
BoxHelper.set( box3 ) // sets the box and calls update()

BoxHelper.setFromObject( object ) // sets the box from the object and calls update()

BoxHelper.update() // updates the geometry from the box
```

2017-04-21 19:15 UTC, mrdoob commented
`Box3Helper` and `PlaneHelper` sounds good to me.

2017-05-01 07:20 UTC, ArjanSchouten commented
Ok. I think it is indeed better to use Box3Helper. I'll close this pr and make a new one asap.

2017-05-01 07:20 UTC, closed without merging

2017-05-22 15:44 UTC, m-schuetz commented
Haven't found it in the dev branch or the PRs yet. Using this here now, in case anyone else needs it:

```
class Box3Helper extends THREE.LineSegments{

	constructor(box, color){

		if ( color === undefined ) color = 0xffff00;

		let indices = new Uint16Array([ 0, 1, 1, 2, 2, 3, 3, 0, 4, 5, 5, 6, 6, 7, 7, 4, 0, 4, 1, 5, 2, 6, 3, 7 ]);
		let positions = new Float32Array( [
			box.min.x, box.min.y, box.min.z,
			box.max.x, box.min.y, box.min.z,
			box.max.x, box.min.y, box.max.z,
			box.min.x, box.min.y, box.max.z,
			box.min.x, box.max.y, box.min.z,
			box.max.x, box.max.y, box.min.z,
			box.max.x, box.max.y, box.max.z,
			box.min.x, box.max.y, box.max.z
		]);

		let geometry = new THREE.BufferGeometry();
		geometry.setIndex( new THREE.BufferAttribute( indices, 1 ) );
		geometry.addAttribute( 'position', new THREE.BufferAttribute( positions, 3 ) );

		let material = new THREE.LineBasicMaterial( { color: color } ) ;
		
		super(geometry, material);
	}

}
```

2017-05-23 22:39 UTC, mrdoob commented
Anyone up for starting `Box3Helper` and `PlaneHelper`?

2017-05-23 23:36 UTC, WestLangley commented
I have a `Box3Helper` working for fat lines. I can file a PR for a `Box3Helper` for native lines.

2017-05-23 23:53 UTC, mrdoob commented
@WestLangley That would be great! Btw, I'll take care of the fat lines PR at the beginning of the next dev cycle (trying to release r86 this week).