misc_animation_keys example update
mrdoob/three.js pull request #11304
Opened 2017-05-09 07:51 UTC by looeee

* Changed the keyframe type to V`ectorKeyframeTrack` for `.position` and `.scale`. 
* Added a `QuaternionKeyframeTrack`, rotating about x axis ( and switched to sphere to box so that rotation is visible). 
* Added some comments. 

It occurred to me that this example should be renamed to misc / animation / basic_use as that is what it's really showing. Then it could also be expanded a little more to show how `AnimationObjectGroup` works, and maybe a couple of other simple things.

2017-05-09 07:57 UTC, Mugen87 commented
For testing: http://rawgit.com/looeee/three.js/misc_anim_keys_example_update/examples/misc_animation_keys.html

2017-05-09 07:59 UTC, Mugen87 requested changes

2017-05-09 07:59 UTC, Mugen87 commented on examples/misc_animation_keys.html
> +        var positionKF = new THREE.VectorKeyframeTrack('.position', [0, 1, 2], [0, 0, 0, 30, 0, 0, 0, 0, 0]);
Formatting does not seem to be consistent here...

2017-05-09 07:59 UTC, Mugen87 commented on examples/misc_animation_keys.html
> +        var quaternionKF = new THREE.QuaternionKeyframeTrack('.quaternion', [0, 1, 2], [qInitial.x, qInitial.y, qInitial.z, qInitial.w, qFinal.x, qFinal.y, qFinal.z, qFinal.w, qInitial.x, qInitial.y,
Some whitespaces are missing at various places: Instead of `[0, 1, 2]` -> `[ 0, 1, 2 ]`

2017-05-09 08:04 UTC, jostschmithals commented
@looeee 👍, but wouldn't it perhaps be nice to switch the single animations on/off via buttons?

2017-05-09 08:09 UTC, Mugen87 commented
> Then it could also be expanded a little more to show how AnimationObjectGroup works, and maybe a couple of other simple things.

Would do this in a separate example.

2017-05-09 08:10 UTC, Mugen87 commented
> but wouldn't it perhaps be nice to switch the single animations on/off via buttons?

I would keep it simple. @looeee's implementation is fine.

2017-05-09 08:22 UTC, looeee commented on examples/misc_animation_keys.html
> +        var quaternionKF = new THREE.QuaternionKeyframeTrack('.quaternion', [0, 1, 2], [qInitial.x, qInitial.y, qInitial.z, qInitial.w, qFinal.x, qFinal.y, qFinal.z, qFinal.w, qInitial.x, qInitial.y,
Seems like I turned on some option that does that automatically when I save the file somehow 🙁

2017-05-09 08:31 UTC, Mugen87 approved these changes

2017-05-14 02:58 UTC, merged

2017-05-14 02:58 UTC, mrdoob commented
Thanks!