Modify Tube geometry to support exporting of the geometry
mrdoob/three.js pull request #11389
Opened 2017-05-25 11:37 UTC by Samsung-Blue

1. Implemented Curve.getPoint function to support any tube geometry and also establish exporting of tube geometry which wasn't possible in the current version.
2. Exporting of tube geometry using ObjectLoader.js is now possible.
3. Example is included in the examples folder ( load_tubegeometry.html )

2017-05-26 00:04 UTC, mrdoob commented
Sounds like you updated `ObjectLoader.js` but the file is not included in the PR. Do you mind doing some clean up? Also, please, do not include builds.

2017-06-05 06:23 UTC, Samsung-Blue commented
Actually I have updated three.js file not ObjectLoader.js because tubeGeometry could not be exported as Curve.getPoint was not implemented in three.js

2017-06-05 09:37 UTC, Mugen87 commented
@Samsung-Blue Please read this article in order to improve your PR: [How to contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js)

2017-06-05 09:43 UTC, Mugen87 requested changes

2017-06-05 09:43 UTC, Mugen87 commented on docs/api/geometries/TubeBufferGeometry.html
> -			THREE.Curve.call( this );
Why have you deleted this line? This breaks the inheritance of the curve object.

2017-06-05 09:43 UTC, Mugen87 commented on docs/api/geometries/TubeBufferGeometry.html
> +			var tx = eval( this.xEq );
The usage of `eval` like this is bad practice...

2017-06-05 09:43 UTC, Mugen87 commented on docs/scenes/geometry-browser.html
> +		<script src="../../build/three.js"></script>
We don't want to use the unminified version of three.js here.

2017-06-05 09:43 UTC, Mugen87 commented on docs/scenes/js/geometry.js
> -
Why do you have deleted this code?

2017-06-05 09:43 UTC, Mugen87 commented on examples/load_tubegeometry.html
> +</html>
The entire code does not respect our code style...

2017-06-05 09:45 UTC, Mugen87 commented
I'm not sure this PR produces any useful benefits. Can you please explain your actual use case? `TubeGeometry` is already able to handle paths defined via curves..

2017-06-06 05:37 UTC, closed without merging