make Matrix(x) error messages correct and consistent
mrdoob/three.js pull request #11409
Opened 2017-05-28 10:08 UTC by aardgoose

pedant mode on.

2017-05-28 10:17 UTC, Mugen87 requested changes

2017-05-28 10:17 UTC, Mugen87 commented on src/math/Matrix3.js
> +			console.error( "THREE.Matrix3: .getInverse no longer takes a Matrix4 argument." );
It should be `.getInverse()` 😉

2017-05-28 10:17 UTC, Mugen87 commented on src/math/Matrix3.js
> +			var msg = "THREE.Matrix3: .getInverse(): can't invert matrix, determinant is 0";
You can remove the colon right after `.getInverse()`

2017-05-28 10:18 UTC, Mugen87 commented on src/math/Matrix4.js
> +			var msg = "THREE.Matrix4: .getInverse(): can't invert matrix, determinant is 0";
And here too...

2017-05-28 17:24 UTC, Mugen87 approved these changes

2017-06-24 03:55 UTC, merged

2017-06-24 03:55 UTC, mrdoob commented
Thanks!