IE: An extra object in data.children in ObjectLoader.parseObject #11432
mrdoob/three.js pull request #11433
Opened 2017-06-02 08:26 UTC by LebedenkoN

Were changed the way of iterating over data.children array in Objectoader.parseObject. Works fine for me. But there is another solution, for example
`for ( var child in data.children ) { if (data.children.hasOwnProperty(child)) { object.add( this.parseObject( data.children[ child ], geometries, materials ) ); } }`

2017-06-02 20:06 UTC, makc commented
or, you could just do for (var i = 0; i < length; i++), like in good old ES4 times

2017-06-03 17:26 UTC, Mugen87 commented
Before merging something it should be clarified why this change is actual necessary. It's still not obvious to me where the `includes` child comes from.

2017-06-03 17:32 UTC, makc commented
@Mugen87 if you have IE, try doing
```javascript
var a = []; // or new Array, or JSON.parse('[]') depending on how data.children is set
for (var b in a) console.log(b);
```

2017-06-09 16:08 UTC, Mugen87 commented
I can't reproduce this on IE11 and Windows 10. The console is empty.

2017-06-09 16:09 UTC, Mugen87 requested changes

2017-06-09 16:09 UTC, Mugen87 commented on src/loaders/ObjectLoader.js
> +
Like @makc said, a classical `for` loop is better here. We are usually not using `forEach`.

2017-06-09 16:13 UTC, LebedenkoN commented
@Mugen87 maybe there is because of my polifill, includes comes from extended Array.prototype

2017-06-11 19:59 UTC, Mugen87 commented
> includes comes from extended Array.prototype

Now everything's clear 😉

2017-06-13 18:20 UTC, mrdoob commented
Hmm... I'm unsure. Should we use `hasOwnProperty()`.
This is more of a javascript issue and people abusing. Correct?

2017-07-06 09:52 UTC, LebedenkoN commented
@mrdoob Looks like that.

2017-07-06 10:22 UTC, Mugen87 requested changes

2017-07-06 10:22 UTC, Mugen87 commented on src/loaders/ObjectLoader.js
> +				for( var i=0; i<data.children.length; i++){
Please respect our codestyle when contributing https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style%E2%84%A2

2017-07-06 12:08 UTC, Mugen87 approved these changes

2017-07-06 17:34 UTC, merged

2017-07-06 17:34 UTC, mrdoob commented
Thanks guys!

2017-11-23 18:26 UTC, davidecarlier commented
I think these changes are creating some issues. 
If I use the ObjectLoader (on v87 and 88) to load a big JSON object (>40MB) I get this error:

![screenshot 4](https://user-images.githubusercontent.com/24975420/33185427-d4fb265e-d082-11e7-9935-1f0977ee8367.png)

With the v86 it worked well, so I'm sticking with it.

2017-11-24 03:29 UTC, mrdoob commented
@davidecarlier do you mind sharing the file that is producing that error?

2017-11-24 17:20 UTC, davidecarlier commented
@mrdoob I figured out what was the problem: my json was containing some empty meshes, with no vertices. 
Version 86 seems to ignore that, it just create empty meshes. 

You can test this issue by loading this empty json. 
[emptyJSON.zip](https://github.com/mrdoob/three.js/files/1502249/emptyJSON.zip)

Anyway I re-exported my scene deleting all the unnecessary parts and now everything works good 😄