Clarified exception warning
mrdoob/three.js pull request #11607
Opened 2017-06-24 20:00 UTC by CarlBateman

2017-06-25 15:30 UTC, Mugen87 requested changes

2017-06-25 15:30 UTC, Mugen87 commented on examples/js/loaders/FBXLoader.js
> +					  throw new Error('FBXLoader: External library Inflate.min.js required, obtain or import from https://github.com/imaya/zlib.js');
Thanks for contributing! When you make a PR, please respect our code style: https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style%E2%84%A2.

In your case:

- Indentation should be tabs (you use just spaces)
- There should be a single space after the opening bracket and  before the closing bracket.

2017-06-26 06:57 UTC, Mugen87 approved these changes

2017-06-26 21:40 UTC, merged

2017-06-26 21:40 UTC, mrdoob commented
Many thanks!