fix DragControl not work on mobile
mrdoob/three.js pull request #11893
Opened 2017-08-05 10:51 UTC by chunnallu

I have fixed DragControl to work on mobile , and verified this not break the exist example --
webgl_interactive_draggablecubes.html

2017-08-06 08:35 UTC, Mugen87 requested changes

2017-08-06 08:35 UTC, Mugen87 commented on examples/js/controls/DragControls.js
> +
Some code style feedback: Indentation should be tabs not spaced.

2017-08-06 08:35 UTC, Mugen87 commented on examples/js/controls/DragControls.js
> +		_mouse.y = - ( (pointer.clientY - rect.top) / rect.height ) * 2 + 1;
Here to...
```javascript
_mouse.x = ( ( pointer.clientX - rect.left ) / rect.width ) * 2 - 1;
```
Reference https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style%E2%84%A2

2017-08-06 08:35 UTC, Mugen87 commented on examples/js/controls/DragControls.js
> +                pointer = event.changedTouches ? event.changedTouches[0] : event;
Please insert spaces between parenthesis like so:
```javascript
event.changedTouches[ 0 ]
```
Besides, it looks like `pointer` is an undeclared variable.

2017-08-06 08:35 UTC, Mugen87 commented on examples/js/controls/DragControls.js
> -
Not necessary to delete this line...

2017-08-06 08:35 UTC, Mugen87 commented on examples/js/controls/DragControls.js
> +
This insertion is not needed...

2017-08-06 08:35 UTC, Mugen87 commented on examples/js/controls/DragControls.js
> +                        _plane.setFromNormalAndCoplanarPoint( _camera.getWorldDirection( _plane.normal ), _selected.position );
Why have added this line? Isn't `_plane` already calculated?

2017-08-06 08:54 UTC, Mugen87 commented
BTW: I'm not sure it's a good idea to use the mouse event handlers for `touchmove`, `touchstart` and `touchend`. Touch interaction proceeds differently than with the mouse. So for example you perform operations on `touchmove` that are actually not required, right?

2017-08-06 09:07 UTC, Mugen87 commented
Have you considered to create new event listeners for `touchmove`, `touchstart` and `touchend`? Maybe this makes the code simpler to read...

2017-08-06 10:34 UTC, chunnallu commented on examples/js/controls/DragControls.js
> +                        _plane.setFromNormalAndCoplanarPoint( _camera.getWorldDirection( _plane.normal ), _selected.position );
That is right !

2017-08-06 10:37 UTC, chunnallu commented
thanks @Mugen87 , I will add some  changes to those code

2017-08-06 10:53 UTC, chunnallu commented
to make some change

2017-08-07 01:49 UTC, chunnallu commented
still some code style issue

2017-08-07 02:19 UTC, chunnallu commented
have fix the code style issue , but have not `create new event listeners for touchmove, touchstart and touchend instead of reusing the mouse event handlers ` , becasuse touch event handler are very similar to mouse event handler , create new event listeners may add some redundancy code @Mugen87

2017-08-07 09:39 UTC, Mugen87 commented
@mrdoob I'm not sure if `THREE.DragControls` needs some refactoring now. As @chunnallu said, new event listeners for touch events may blow up the code. On the other side, it would be easier to separate the logic. Redundant code could be implemented in new shared methods.

For example, `THREE.DragControls` fires `hoveron` and `hoveroff` events which makes sense for mouse controls but not for touch devices. I think it would be nice if touch related event listeners don't try to fire these events.

2017-08-08 20:31 UTC, mrdoob commented
How about switching to pointer events?

2017-08-09 01:53 UTC, chunnallu commented
> How about switching to pointer events?

Is it mean that refactor event type `hoveron` to  event type `pointer` ? like below :

from :
```
scope.dispatchEvent( { type: 'hoveron', object: object } );
```
to : 
```
scope.dispatchEvent( { type: 'pointer', object: object } );
```
@mrdoob @Mugen87

2017-08-09 09:15 UTC, Mugen87 commented
I think @mrdoob means:

- `pointerdown` replaces  `touchstart` and `mousedown`
- `pointerup` replaces `touchend` and `mouseup`
- `pointermove` replaces `touchmove` and `mousemove`

@chunnallu Do you think you can change so `THREE.DragControl` uses pointer events.

As i mentioned before, i still think it makes no sense that touch devices fire hover events. We maybe should query [pointerEvent.pointerType](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerType) and only fire hover events for the value `mouse`.

2017-08-09 15:37 UTC, chunnallu commented
maybe i can ! In fact i am a fresh coder , i do this maybe slow with many error，haha ! so  i think the best way is that you or someone other in rich experience to change the code @Mugen87

2017-08-09 16:18 UTC, Mugen87 commented
@chunnallu Give it a try! This is the best way to learn programming :blush:

2017-08-10 10:59 UTC, chunnallu commented
thanks ! haha , can't not aggre more!

2017-08-13 04:05 UTC, chunnallu commented
new commit : 

- separate the logic of touch event and mouse event , create new event listeners for touchend

- add `mouseleave` event 

- rename `onDocumentMouseUp` handler to `onDocumentMouseCancel` , so it can use to handle `mouseup` and 'mouseleave` event

beside , use pointer events seem to be a little unclear , so  i still to separate the event handles. :stuck_out_tongue_winking_eye:

2017-08-13 11:30 UTC, Mugen87 commented
I've realized right now that the browser support for Pointer events is not good enough, see http://caniuse.com/#feat=pointer

So for the moment it's maybe better to stay at `mouse` and `touch` events even if this means some redundant code.

2017-08-15 09:40 UTC, Mugen87 approved these changes

2017-08-16 03:12 UTC, merged

2017-08-16 03:12 UTC, mrdoob commented
Thanks!