fix of bug #11876
mrdoob/three.js pull request #11965
Opened 2017-08-16 08:32 UTC by pablolh

https://github.com/mrdoob/three.js/issues/11876#issuecomment-322426016

2017-08-16 09:28 UTC, Mugen87 commented
Um, why is this commit in your PR: f83fe541f6aac09e9a94943884f7d698dd55ba32

2017-08-16 09:29 UTC, Mugen87 requested changes

2017-08-16 09:29 UTC, Mugen87 commented on src/audio/Audio.js
> +		if( this.isPlaying ) {
just some code style issues. please write it like this:
```javascript
if ( this.isPlaying === true ){

   // code 

}
```

2017-08-16 09:29 UTC, Mugen87 commented on src/audio/Audio.js
> +			this.isPlaying = false;
one newline after this statement.

2017-08-16 14:21 UTC, donmccurdy commented
@pablolh you may have gotten f83fe54 in here by starting from `master` branch instead of `dev`? I think `git revert f83fe54` would fix it...

2017-08-18 13:45 UTC, Mugen87 commented
@pablolh Maybe it's best to start with a fresh PR. As @donmccurdy said, checkout your feature branch from latest `dev` and then apply your changes. Before you submit the PR, you can validate if the list of commits is correct.

2017-08-18 13:45 UTC, closed without merging