GLTFLoader - Adding support for normalScale as part of the normalTexture
mrdoob/three.js pull request #12017
Opened 2017-08-23 01:43 UTC by calrk

The Unity > GLTF exporter allows the scales of the normals to be set on the normalTexture. 

I made a sample model with the left sphere at 0.5 scale, the center at 1.0 scale and the right at 2.0 scale.
[Spheres_20170823.zip](https://github.com/mrdoob/three.js/files/1243854/Spheres_20170823.zip)

The view in unity:
![unity](https://user-images.githubusercontent.com/2245579/29594505-cefbc0e6-87f4-11e7-918f-b55c3207223a.JPG)

However this property is not read by the current GLTFLoader
The result in gltf viewer - https://gltf-viewer.donmccurdy.com
![threejs gltf](https://user-images.githubusercontent.com/2245579/29594522-e836f1b6-87f4-11e7-9b13-4676d9eea589.JPG)

I'm adding this small change to read the 'scale' property of a normalTexture:
![threejs gltf - fixed](https://user-images.githubusercontent.com/2245579/29594711-0abbf4c4-87f6-11e7-9970-4339e1b41fc5.JPG)

Let me know what you think,
Clark

2017-08-23 03:35 UTC, donmccurdy requested changes
On [line 619](https://github.com/calrk/three.js/blob/d28ffdb5cb30cb8125f736dc710d9d270b350cbe/examples/js/loaders/GLTFLoader.js#L619), there's another reference to normalScale that I think needs to be changed to:

```js
material.normalScale = params.normalScale || new THREE.Vector2( 1, 1 );
```

... to have this fix also work on spec-gloss materials.

Thanks!

2017-08-23 03:43 UTC, calrk commented
Sure, added that in now.

2017-08-23 03:44 UTC, donmccurdy approved these changes
Nice, thanks! 🙂

2017-08-23 04:01 UTC, mrdoob commented
> ```js
> material.normalScale = params.normalScale || new THREE.Vector2( 1, 1 );
> ```

Hmm... `params.normalScale` can be a `THREE.Vector2`?

2017-08-23 04:08 UTC, donmccurdy commented
If `params.normalScale` is defined, it will be coming from the `materialParams.normalScale = ...` line that @calrk just added. `materialParams` is passed into the `createMaterial()` method as `params`.

2017-08-23 04:11 UTC, takahirox commented on examples/js/loaders/GLTFLoader.js
> +				if ( material.normalTexture.scale ) {
`material.normalTexture.scale` can't be zero?

2017-08-23 04:17 UTC, donmccurdy commented on examples/js/loaders/GLTFLoader.js
> +				if ( material.normalTexture.scale ) {
Technically it could, sure. Let's do `material.normalTexture.scale !== undefined` then?

2017-08-23 04:20 UTC, takahirox commented on examples/js/loaders/GLTFLoader.js
> +				if ( material.normalTexture.scale ) {
Yeah, I think it should be.

2017-08-23 05:20 UTC, calrk commented
Ok, added in that check now too.

2017-08-23 19:35 UTC, mrdoob commented
Hmm, maybe the logic could be simplified?

```js
material.normalScale = params.normalScale;
```

And then...

```js
materialParams.normalScale = new THREE.Vector2( 1, 1 );

if ( material.normalTexture.scale !== undefined ) {
	materialParams.normalScale.set( material.normalTexture.scale, material.normalTexture.scale );
}
```

2017-08-24 00:20 UTC, calrk commented
I changed the structure of the default setting to be consistent with the other properties.

Did we want to keep this part in case this function is used in future elsewhere, so people don't have to define params.normalScale?
````
material.normalScale = params.normalScale === undefined ? new THREE.Vector2( 1, 1 ) : params.normalScale;
````

I'm not sure what happens if it was set to `null` or `undefined`, so just to be sure it gets the correct default?

2017-08-24 01:45 UTC, mrdoob commented on examples/js/loaders/GLTFLoader.js
> +				material.normalScale = params.normalScale === undefined ? new THREE.Vector2( 1, 1 ) : params.normalScale;
How about...

```js
if ( params.normalScale ) material.normalScale = params.normalScale;
```

2017-08-24 02:00 UTC, calrk commented on examples/js/loaders/GLTFLoader.js
> +				material.normalScale = params.normalScale === undefined ? new THREE.Vector2( 1, 1 ) : params.normalScale;
Sure, looks good. Changing it now.

2017-08-24 20:01 UTC, merged

2017-08-24 20:01 UTC, mrdoob commented
Thanks!