Fix Object3D, Material and Texture toJSON method
mrdoob/three.js pull request #12196
Opened 2017-09-14 11:32 UTC by autra

This makes their toJSON method compatible with JSON.stringify.

This PR does not attempt to fix `AnimationClip` and `KeyframeTrack` `toJSON` objects, as they are not attached to their prototype and won't get used in a JSON.stringify call anyway.

Fixes #8581.

2017-09-14 11:41 UTC, Mugen87 requested changes

2017-09-14 11:41 UTC, Mugen87 commented on src/materials/Material.js
> +		var isRoot = (meta === undefined || typeof meta === 'string' );
Just some code style issues: There must be a space inside this paren.
```javascript
var isRoot = ( meta === undefined || typeof meta === 'string' );
```

2017-09-14 11:41 UTC, Mugen87 commented on src/textures/Texture.js
> +		if ( !isRootObject ) {
Block must be padded by blank lines:
```javascript
if ( ! isRootObject ) {

    meta.textures[ this.uuid ] = output;

}
```

2017-09-14 11:41 UTC, Mugen87 commented on src/textures/Texture.js
> +		var isRootObject = (meta === undefined || typeof meta === 'string' );
same here...

2017-09-14 11:41 UTC, Mugen87 commented on src/textures/Texture.js
> +		if ( !isRootObject && meta.textures[ this.uuid ] !== undefined ) {
Unary operator '!' must be followed by whitespace. These happens several times in your code.

```javascript
if ( ! isRootObject && meta.textures[ this.uuid ] !== undefined ) {
```

2017-09-14 11:42 UTC, Mugen87 commented on src/textures/Texture.js
> +		if ( !isRootObject ) {
You can use `npm run lint` to ensure your code is free of warnings...

2017-09-14 11:54 UTC, autra commented
@Mugen87 I forgot to execute `npm run lint` before opening, sorry for that :-)

2017-09-14 11:55 UTC, Mugen87 approved these changes

2017-09-15 08:49 UTC, autra commented
Thanks @Mugen87 ! Is there any action I need to do to get this merged?

2017-09-15 09:09 UTC, Mugen87 commented
@autra No, but @mrdoob needs to review this, too.

2017-09-22 23:05 UTC, merged

2017-09-22 23:05 UTC, mrdoob commented
Thanks!