add link to slack-signup
mrdoob/three.js pull request #12252
Opened 2017-09-21 19:05 UTC by usefulthink

2017-09-21 20:06 UTC, Fasani requested changes

2017-09-21 20:06 UTC, Fasani commented on index.html
>  				<a href="http://webchat.freenode.net/?channels=three.js">chat</a><br />
Might be also helpful to change this link to "irc" rather than "chat".

2017-09-21 20:36 UTC, Fasani approved these changes

2017-09-21 21:50 UTC, merged

2017-09-21 21:50 UTC, mrdoob commented
Thanks!

2017-09-21 23:56 UTC, looeee commented
Shouldn't the slack link be https://threejs.slack.com ?

2017-09-22 06:13 UTC, Fasani commented
@looeee that is the slack url but @usefulthink has created a small self invite app. You can’t get into slack without an invite and the app hosted on heroku allows you to invite yourself. It’s a common practice. Give it a try and I will see you on the inside! :-)

2017-09-22 06:58 UTC, looeee commented
OK, that makes sense 😄