Fix warning on spaces log (#9317)
mrdoob/three.js pull request #12590
Opened 2017-11-06 09:33 UTC by olivierchatry

2017-11-06 09:58 UTC, takahirox commented on src/renderers/WebGLRenderer.js
>  		_canvas.removeEventListener( 'webglcontextlost', onContextLost, false );
What's this for?

2017-11-06 10:05 UTC, olivierchatry commented
This is super weird, old commit that have already been integrated I think (
was a memory leak when disposing / recreating )

On 6 Nov 2017 10:59 am, "Takahiro" <notifications@github.com> wrote:

> *@takahirox* commented on this pull request.
> ------------------------------
>
> In src/renderers/WebGLRenderer.js
> <https://github.com/mrdoob/three.js/pull/12590#discussion_r149035156>:
>
> > @@ -502,6 +502,11 @@ function WebGLRenderer( parameters ) {
>
>  	this.dispose = function () {
>
> +		transparentObjects = [];
> +		transparentObjectsLastIndex = -1;
> +		opaqueObjects = [];
> +		opaqueObjectsLastIndex = -1;
> +
>  		_canvas.removeEventListener( 'webglcontextlost', onContextLost, false );
>
> What's this for?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrdoob/three.js/pull/12590#pullrequestreview-74365427>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNXG6jQ2Fc7p5ZLTGndcuBZ2DR5uOgvks5sztiLgaJpZM4QS9Ba>
> .
>

2017-11-06 10:29 UTC, Mugen87 commented
Do you want to solve the following issue with your PR? #11138

If so, i think it's better to fix this on Chrome side.

2017-11-06 10:33 UTC, Mugen87 commented
I've realized we have two issues for the same thing. I'll close #9317 so #11138 is the leading one.

2017-11-06 10:33 UTC, olivierchatry commented
Hum, you mean that chrome should do what the PR does ? I did it because it
was bothersome, and can be easily remove if chrome fix it.

On Mon, Nov 6, 2017 at 11:30 AM, Michael Herzog <notifications@github.com>
wrote:

> Do you want to solve the following issue with your PR? #11138
> <https://github.com/mrdoob/three.js/issues/11138>
>
> If so, i think it's better to fix this on Chrome side.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrdoob/three.js/pull/12590#issuecomment-342107887>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNXG9tNo-RdUAQyKR_s5jwySiWZ2Jiiks5szt_BgaJpZM4QS9Ba>
> .
>

2017-11-06 10:37 UTC, Mugen87 commented
There is already a filed bug at the chromium project. IMO, it makes more sense to request an implementation of this specific issue.

https://bugs.chromium.org/p/chromium/issues/detail?id=711520

2017-11-06 10:48 UTC, olivierchatry commented
Well, it took me 3 seconds to make this fix, we are already discussing it
for more than 5 minutes and the chrome bug have been filled in april, with
people arguing if it is a threejs issue, or whatever.

This is this code that needs to do the same thing as I do :

https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/webgl/WebGLRenderingContextBase.cpp?sq=package:chromium&l=3248


On Mon, Nov 6, 2017 at 11:38 AM, Michael Herzog <notifications@github.com>
wrote:

> There is already a filed bug at the chromium project. IMO, it makes more
> sense to request an implementation of this specific issue.
>
> https://bugs.chromium.org/p/chromium/issues/detail?id=711520
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrdoob/three.js/pull/12590#issuecomment-342109858>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNXG04kPTcQ9hbvg-k6QUKKOPGVZiTLks5szuGTgaJpZM4QS9Ba>
> .
>

2017-11-06 10:50 UTC, olivierchatry commented
From this one :

https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/webgl/GLStringQuery.h?sq=package:chromium&l=17

Anyway the return value is driver dependant. So if a manufacturer decide to
fill with '*' when there is nothing to be reported, I think it should be
the 3d engine, not the webgl implementation, that fix that.

On Mon, Nov 6, 2017 at 11:48 AM, Olivier Chatry <olivier.chatry@gmail.com>
wrote:

> Well, it took me 3 seconds to make this fix, we are already discussing it
> for more than 5 minutes and the chrome bug have been filled in april, with
> people arguing if it is a threejs issue, or whatever.
>
> This is this code that needs to do the same thing as I do :
>
> https://cs.chromium.org/chromium/src/third_party/
> WebKit/Source/modules/webgl/WebGLRenderingContextBase.cpp?
> sq=package:chromium&l=3248
>
>
> On Mon, Nov 6, 2017 at 11:38 AM, Michael Herzog <notifications@github.com>
> wrote:
>
>> There is already a filed bug at the chromium project. IMO, it makes more
>> sense to request an implementation of this specific issue.
>>
>> https://bugs.chromium.org/p/chromium/issues/detail?id=711520
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mrdoob/three.js/pull/12590#issuecomment-342109858>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/ABNXG04kPTcQ9hbvg-k6QUKKOPGVZiTLks5szuGTgaJpZM4QS9Ba>
>> .
>>
>
>

2017-11-06 10:51 UTC, olivierchatry commented
Also, *@takahirox I realized I never did a pull request for the other bug
... *

On Mon, Nov 6, 2017 at 11:50 AM, Olivier Chatry <olivier.chatry@gmail.com>
wrote:

> From this one :
>
> https://cs.chromium.org/chromium/src/third_party/
> WebKit/Source/modules/webgl/GLStringQuery.h?sq=package:chromium&l=17
>
> Anyway the return value is driver dependant. So if a manufacturer decide
> to fill with '*' when there is nothing to be reported, I think it should be
> the 3d engine, not the webgl implementation, that fix that.
>
> On Mon, Nov 6, 2017 at 11:48 AM, Olivier Chatry <olivier.chatry@gmail.com>
> wrote:
>
>> Well, it took me 3 seconds to make this fix, we are already discussing it
>> for more than 5 minutes and the chrome bug have been filled in april, with
>> people arguing if it is a threejs issue, or whatever.
>>
>> This is this code that needs to do the same thing as I do :
>>
>> https://cs.chromium.org/chromium/src/third_party/WebKit/
>> Source/modules/webgl/WebGLRenderingContextBase.cpp?sq=
>> package:chromium&l=3248
>>
>>
>> On Mon, Nov 6, 2017 at 11:38 AM, Michael Herzog <notifications@github.com
>> > wrote:
>>
>>> There is already a filed bug at the chromium project. IMO, it makes more
>>> sense to request an implementation of this specific issue.
>>>
>>> https://bugs.chromium.org/p/chromium/issues/detail?id=711520
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/mrdoob/three.js/pull/12590#issuecomment-342109858>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe-auth/ABNXG04kPTcQ9hbvg-k6QUKKOPGVZiTLks5szuGTgaJpZM4QS9Ba>
>>> .
>>>
>>
>>
>

2017-11-06 11:01 UTC, Mugen87 commented
@kenrussell Any chances of a soon fix for this issue?

https://bugs.chromium.org/p/chromium/issues/detail?id=711520

2017-11-06 11:06 UTC, olivierchatry commented
IMHO, I think it should be the 3d engine, not the webgl low level
implementation that fix that. But it should also be a 5 minutes fix  ( at
least the code, not the whole regression testing ) in blink code.

On Mon, Nov 6, 2017 at 12:02 PM, Michael Herzog <notifications@github.com>
wrote:

> @kenrussell <https://github.com/kenrussell> Any chances of a soon fix for
> this issue?
>
> https://bugs.chromium.org/p/chromium/issues/detail?id=711520
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrdoob/three.js/pull/12590#issuecomment-342115929>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNXG5AH8cNofstBTKMzzgLjnxp2F1-zks5szudCgaJpZM4QS9Ba>
> .
>

2017-11-06 16:22 UTC, Mugen87 commented
@olivierchatry I just want to add that i generally prefer a fix in Chrome. But if the Chromium guys won't respond, i vote for a fix in the library. In any event, thanks for pushing this issue forward 👍

2017-11-19 12:03 UTC, Mugen87 commented
Okay, i vote for a change in the library. It does not look like we get a fix for Chrome in the near future. But we only should merge this PR without the following commit: 513fa23086d1ced9f51b62476c4b5d9377807ea1

2017-11-19 12:20 UTC, olivierchatry commented
Well not sure what is going on with this one, I think it was already
integrated.

https://github.com/mrdoob/three.js/issues/8987
https://github.com/mrdoob/three.js/pull/9011

On 19 Nov 2017 1:03 pm, "Michael Herzog" <notifications@github.com> wrote:

> Okay, i vote for a change in the library. It does not look like we get a
> fix for Chrome in the near future. But we only should merge this PR without
> the following commit: 513fa23
> <https://github.com/mrdoob/three.js/commit/513fa23086d1ced9f51b62476c4b5d9377807ea1>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrdoob/three.js/pull/12590#issuecomment-345511394>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNXG2yWKbZDOhtJM0FE1ZkLHAzFOnN7ks5s4BkkgaJpZM4QS9Ba>
> .
>

2017-11-21 16:06 UTC, haroldiedema requested changes

2017-11-21 16:06 UTC, haroldiedema commented on src/renderers/webgl/WebGLProgram.js
> +	var programLog = gl.getProgramInfoLog( program ).replace(/\0/g, '').trim();
This isn't going to fix this issue for all cases.

As the developers at chromium stated, the information here is driver implementation specific. In my case, this returns 4 blank lines on some occasions.

Also maybe it's not a good idea to use regex in this part of the code for performance reasons.

2017-11-21 16:12 UTC, olivierchatry commented
From my test, it should solve your issue ( trim take cares of the empty
lines as well ). I tested it in nodejs, but I might be wrong. For the
performance bit, I would argue that it will not really impact anything, but
I'm sure a profile will give way better number.

On Tue, Nov 21, 2017 at 5:08 PM, Harold Iedema <notifications@github.com>
wrote:

> *@haroldiedema* requested changes on this pull request.
> ------------------------------
>
> In src/renderers/webgl/WebGLProgram.js
> <https://github.com/mrdoob/three.js/pull/12590#discussion_r152321703>:
>
> > @@ -540,9 +540,9 @@ function WebGLProgram( renderer, extensions, code, material, shader, parameters
>
>  	gl.linkProgram( program );
>
> -	var programLog = gl.getProgramInfoLog( program );
> -	var vertexLog = gl.getShaderInfoLog( glVertexShader );
> -	var fragmentLog = gl.getShaderInfoLog( glFragmentShader );
> +	var programLog = gl.getProgramInfoLog( program ).replace(/\0/g, '').trim();
>
> This isn't going to fix this issue for all cases.
>
> As the developers at chromium stated, the information here is driver
> implementation specific. In my case, this returns 4 blank lines on some
> occasions.
>
> Also maybe it's not a good idea to use regex in this part of the code for
> performance reasons.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrdoob/three.js/pull/12590#pullrequestreview-78165804>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNXG-JShFGOCwRl_c67f15AnYJBtmljks5s4vV1gaJpZM4QS9Ba>
> .
>

2017-12-30 18:48 UTC, Mugen87 commented
see #12950

2017-12-30 18:48 UTC, closed without merging