fixed to read "serial" field in PDB files.
mrdoob/three.js pull request #12620
Opened 2017-11-10 08:04 UTC by kenkiku1021

This PR fix #12619 
To read serial field in PDB files.

2017-11-12 16:11 UTC, Mugen87 requested changes

2017-11-12 16:11 UTC, Mugen87 commented on examples/js/loaders/PDBLoader.js
> +				atoms[index] = [ x, y, z, CPK[ e ], capitalize( e ) ];
Code style: `atoms[ index ]`.

2017-11-12 16:11 UTC, Mugen87 commented
The existing example works with these changes: http://rawgit.com/kenkiku1021/three.js/PDBLoader-fix/examples/webgl_loader_pdb.html

2017-11-12 16:18 UTC, Mugen87 commented
See http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

@kenkiku1021 I guess the loader parses now this section, right?

```
 7 - 11        Integer       serial       Atom  serial number.
```

2017-11-13 00:12 UTC, kenkiku1021 commented
@Mugen87 That's right. The loader should parse the serial section.

2017-11-13 00:13 UTC, kenkiku1021 commented
I fixed coding style for 'three.js'.

2017-11-13 09:58 UTC, Mugen87 commented
Looks good! 👍

2017-11-13 09:59 UTC, Mugen87 approved these changes

2017-11-15 00:14 UTC, merged

2017-11-15 00:14 UTC, mrdoob commented
Thanks!