Add `powerPreference` preference #12533
mrdoob/three.js pull request #12753
Opened 2017-11-26 11:12 UTC by luruke

2017-11-26 11:23 UTC, luruke commented
I had to move `webglcontextlost` and `webglcontextrestored` events listener *before* the creation of the gl context.

According to the spec:
> At WebGLRenderingContext creation time, this attribute will be ignored if no event listeners exist which would handle both "webglcontextlost" and "webglcontextrestored" events dispatched to the canvas element.

Honestly I had hard time to figure out any difference on my machine `MacBook Pro (13-inch, 2016) - 10.13.1, Intel Iris Graphics 540 1536 MB`.

I guess this parameter is taken into consideration for machine with multiple GPU?

2017-11-26 12:52 UTC, Mugen87 requested changes

2017-11-26 12:52 UTC, Mugen87 commented on src/renderers/WebGL2Renderer.js
> +    _powerPreference = parameters.powerPreference !== undefined ? parameters.powerPreference : 'default';
Looks like some formatting issues...

2017-11-27 07:36 UTC, mrdoob commented on src/renderers/WebGL2Renderer.js
> +    		_alpha = parameters.alpha !== undefined ? parameters.alpha : false,
Seems like there is a mix of spaces and tabs for indentation in these lines...

2017-11-27 07:36 UTC, mrdoob commented on src/renderers/WebGL2Renderer.js
> +			powerPreference: _powerPreference,
The comma at the end is not needed.

2017-11-27 07:36 UTC, mrdoob commented on src/renderers/WebGLRenderer.js
> +			powerPreference: _powerPreference,
The comma at the end is not needed.

2017-11-27 07:38 UTC, mrdoob commented
> I had to move `webglcontextlost` and `webglcontextrestored` events listener *before* the creation of the gl context.
>
> According to the spec:
>> At WebGLRenderingContext creation time, this attribute will be ignored if no event listeners exist which would handle both "webglcontextlost" and "webglcontextrestored" events dispatched to the canvas element.

I don't understand... Do you mind giving more context?

2017-11-27 09:11 UTC, luruke commented
@mrdoob sorry for those silly indentations issues.

From the spec: https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1
What I understand is that you must handle `webglcontextlost` and `webglcontextrestored` before the creation of the context, otherwise the powerPreference is ignored.

A related issue:
https://github.com/KhronosGroup/WebGL/issues/2343

2017-11-28 20:50 UTC, luruke commented
@mrdoob @Mugen87 
You can find more info here:
https://www.khronos.org/webgl/public-mailing-list/public_webgl/1703/msg00021.php

2017-11-28 20:57 UTC, Mugen87 commented
see #2343
and
> You MUST have a registered event handler for the webglcontextlost and webglcontextrestored events if you want the user agent to respect your request for high-performance.

@luruke So yes, i think the implementation is correct.

2017-11-28 20:58 UTC, Mugen87 approved these changes

2017-11-28 21:08 UTC, Mugen87 commented
Um, maybe we should add a comment. Something like:
`
// event listeners must be registered before WebGL Context is created, see #12753
`
Otherwise it's easy to overlooked this dependency...

2017-11-29 05:32 UTC, mrdoob commented
Perfect!

2017-11-29 05:33 UTC, merged

2017-11-29 05:33 UTC, mrdoob commented
Thanks!