Trying to fix geometry tests
mrdoob/three.js pull request #12781
Opened 2017-11-29 11:32 UTC by OndrejSpanel

This PR starts effort to fix geometry tests. The commit provides an obvioius fix - the required `path` parameter was not provided for `TubeGeometry`. The test executes now a bit more, but it still does not pass, failed parts are:

> 4. properties are equal
> 23. geometry matching source uuid not in output
 
If someone can give an advice how to fix them, I will be happy to continue with the fix. I will try to continue anyway, but without advice I am afraid it will require a bit more effort.

2017-11-29 12:29 UTC, Mugen87 requested changes

2017-11-29 12:29 UTC, Mugen87 commented on test/unit/src/geometries/TubeGeometry.tests.js
> +            var path = new LineCurve3(new Vector3(0, 0, 0), new Vector3(0, 1, 0));
Please improve the code style in your PRs. Als ensure to use hard tabs and not soft tabs. More information here:

https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js

2017-11-29 13:21 UTC, OndrejSpanel commented
I hope I have fixed all code style issues.

2017-11-29 13:52 UTC, Mugen87 commented
Much better 👍 . Please check #12778, too.

2017-11-30 06:35 UTC, mrdoob commented on test/unit/src/geometries/ShapeGeometry.tests.js
> +import {Shape} from '../../../../src/extras/core/Shape';
Minor thing...

```js
import { Shape } from '../../../../src/extras/core/Shape';
```

2017-11-30 06:36 UTC, mrdoob commented on test/unit/src/geometries/TubeGeometry.tests.js
> +import {Vector3} from '../../../../src/math/Vector3'
Same here...

```js
import { LineCurve3 } from '../../../../src/extras/curves/LineCurve3'
import { Vector3 } from '../../../../src/math/Vector3'
```

2017-11-30 09:39 UTC, Mugen87 approved these changes

2017-12-01 11:04 UTC, merged

2017-12-01 11:04 UTC, mrdoob commented
Thanks!