fix video-textures for cached/fast video-loads
mrdoob/three.js pull request #13053
Opened 2018-01-06 14:59 UTC by usefulthink

When creating a video-texture from an existing video-element on the
page, the video might have already reached a playable state. In this
case, the `loadeddata` event has already been fired before the
video-texture was created and the texture will never become renderable.

This can be detected if the video has a `readyState >= 2`
(HAVE_CURRENT_DATA) when initializing the texture.

2018-01-06 15:34 UTC, Mugen87 requested changes

2018-01-06 15:34 UTC, Mugen87 commented on src/textures/VideoTexture.js
> +	if( video.readyState >= HTMLMediaElement.HAVE_CURRENT_DATA ) {
Please write it like this:
```
if ( video.readyState >= video.HAVE_CURRENT_DATA ) {
```

2018-01-06 15:44 UTC, usefulthink commented
done.

2018-01-06 17:32 UTC, mrdoob commented
Hmm, I think this is becoming a bit spaghetti... I'll try a refactor...

2018-01-06 17:53 UTC, mrdoob commented
Okay, now the renderer will run the `update()` for every `VideoTexture` that it finds (only once per frame). I think it should be more robust now. Do you mind checking if it fixes your use case?

2018-01-06 18:31 UTC, Mugen87 commented
Much better than before 👍

2018-01-06 20:40 UTC, usefulthink commented
awesome, solves the problem as well :D Also a much better solution, thanks! 

@mrdoob this makes me think, it might even be generalized into "dynamic textures" (i.e. any texture that has `texture.isDynamic = true;` and a function `texture.update()` defined). Could be useful for more than just video..

2018-01-06 20:40 UTC, closed without merging

2018-01-08 23:28 UTC, mrdoob commented
@usefulthink that is true... but lets hold on this for a bit until we feel is stable enough 😅