Box3: new method intersectsTriangle #13064
mrdoob/three.js pull request #13079
Opened 2018-01-10 08:35 UTC by matthias-w

The PR adds the method `Box3.intersectsTriangle`. The method tests whether the axis aligned box intersects with the given triangle. The algorithm used is based on separating axis theorem (SAT). This test is useful in computational geometry. I use it for generating a spatial index for `THREE.BufferGeometry`.

2018-01-10 22:04 UTC, mrdoob commented
Would you like to also add a example that uses this?

2018-01-11 11:00 UTC, Mugen87 commented
We also need these things:

- Updated [docs](https://threejs.org/docs/index.html#api/math/Box3)
- Updated [unit test](https://github.com/mrdoob/three.js/blob/dev/test/unit/src/math/Box3.tests.js)
- Better code style. The code is not entirely conform to the project's [code style](https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style%E2%84%A2).
- We also should add the counter method `Triangle.intersectsBox()` (and update the corresponding doc page and unit test)

2018-01-11 11:02 UTC, Mugen87 commented on src/math/Box3.js
> +		function satForAxes (axes) {
We should move this function to module space, see 166ba2f5e6d69da5efb8a9c214f59a1a18ce0ee3

2018-01-11 16:29 UTC, matthias-w commented
@Mugen87 I will see to your mentioned open issues. Just one question: Can you please give me a hint regarding code style issues? I used the online code beautifier so I thought the code would be compliant to the required style rules.

@mrdoob Do you mean an example for a specific use case for the [THREE example page](https://threejs.org/examples/)? The only use case I currently have is the mentioned spatial index creation (Octree) for `THREE.BufferGeometry`. I use this approach for speeding up VRController-Mesh collision detection in my VR application.

2018-01-12 12:48 UTC, Mugen87 requested changes

2018-01-12 12:48 UTC, Mugen87 commented on src/math/Box3.js
> +		function satForAxes (axes) {
```javascript
function satForAxes( axes ) {
```

2018-01-12 12:48 UTC, Mugen87 commented on src/math/Box3.js
> +		return function intersectsTriangle ( triangle ) {
```javascript
return function intersectsTriangle( triangle ) {
```

2018-01-12 12:48 UTC, Mugen87 commented on src/math/Box3.js
> +			this.getCenter(center);
```javascript
this.getCenter( center );
```

2018-01-12 17:32 UTC, Mugen87 commented
👍

2018-01-15 11:10 UTC, Mugen87 approved these changes

2018-01-18 01:16 UTC, merged

2018-01-18 01:18 UTC, mrdoob commented
> @mrdoob Do you mean an example for a specific use case for the [THREE example page](https://threejs.org/examples/)? The only use case I currently have is the mentioned spatial index creation (Octree) for `THREE.BufferGeometry`. I use this approach for speeding up VRController-Mesh collision detection in my VR application.  

Yeah. I think it'll be good to have some example using it so other people have a hint of what to do with it.

Thanks!