Combine WebGL Lines Colors and Splines Examples
mrdoob/three.js pull request #13563
Opened 2018-03-11 05:43 UTC by XanderLuciano

#13439 - [Examples Cleanup](https://github.com/mrdoob/three.js/issues/13439#issuecomment-372059303)

> @mrdoob These two can be combined (Both in the same scene)
> https://threejs.org/examples/canvas_lines_colors.html
> https://threejs.org/examples/canvas_lines_colors_2d.html

This PR combines the two scenes of WebGL_lines_colors and WebGL_lines_splines into a single example.

Lines Colors had additional effects applied to the scene which were unnecessary so those were not merged.

Lines Spinles used `BufferGeometry` while Lines Colors used `Geometry`, however I have include both in this example as I think it makes for a better example to show both methods of adding color to `Three.Line`.

2018-03-11 06:39 UTC, WestLangley commented
Ephemeral test link: https://rawgit.com/XanderLuciano/three.js/dev/examples/webgl_lines_colorsplines.html

2018-03-11 09:09 UTC, Mugen87 requested changes

2018-03-11 09:09 UTC, Mugen87 commented on examples/webgl_lines_colorsplines.html
> +                    buffGeometry2 = new THREE.BufferGeometry();
Can you please check your formatting? Looks like your are mixing soft and hard tabs. Please use just hard tabs.

2018-03-11 17:36 UTC, WestLangley commented
>Lines Splines used BufferGeometry while Lines Colors used Geometry, however I have include both in this example as I think it makes for a better example

My intention was to remove `Geometry` from the examples in favor of `BufferGeometry`. The reason is that, at some point, `Geometry` will no longer be renderable. Encouraging users to use `BufferGeometry` now will make for an easier transition.

However, we should do whatever @mrdoob feels is best.

2018-03-11 19:19 UTC, XanderLuciano commented
@WestLangley Not a problem at all, I left the splines example in the `BufferGeometry` section, so removing the `Geometry` portion is fairly straightforward and won't affect the rest of the code if mrdoob wants to have `BufferGeometry` only.

@Mugen87 My IDE was set to spaces, I switched it to tabs and updated the PR. Sorry about that!

2018-03-11 19:31 UTC, Mugen87 approved these changes

2018-03-14 05:07 UTC, mrdoob commented
> @mrdoob Remove or keep `Geometry` in these examples?

I would vote moving to `BufferGeometry`. But no need to be done in this PR.

However, I think I would keep the filename `webgl_lines_colors.html` instead of `webgl_lines_colorspline.html`.

2018-03-14 15:06 UTC, merged

2018-03-14 15:06 UTC, mrdoob commented
Thanks!