PCDLoader decoder compatibility
mrdoob/three.js pull request #13764
Opened 2018-04-04 08:33 UTC by yomotsu

PCDLoader example doesn't work in IE and Edge. This P-R is to solve the problem.

PCD file can contain binary.

> DATA - specifies the data type that the point cloud data is stored in. As of version 0.7, two data types are supported: ascii and binary. See the next section for more details.

via http://pointclouds.org/documentation/tutorials/pcd_file_format.php

If the PCD file is binary version,  it causes a garbled and `decodeURIComponent` that is a fallback for [`TextDecorder` unsupported browsers](https://github.com/mrdoob/three.js/blob/dev/src/loaders/LoaderUtils.js#L28), such as IE and Edge will return "malformed error"

Fortunately, the header section is always ascii format, and `decodeURIComponent` and `escape` is  unnecessary.

This patch is adding a decoder in PCDLoader, rather than using `THREE.LoaderUtils.decodeText`

2018-04-04 14:31 UTC, donmccurdy commented
It would be nice to patch `LoaderUtils.decodeText` for this case somehow. Perhaps:

```js
LoaderUtils.decodeText( array, isASCII = true );
```

Using `decodeURIComponent( escape( s ) );` for multi-byte characters was always a bit of a hack for Edge+IE11. Edge is [working toward TextDecoder](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/encodingstandard/) support now, or another option is to use the [text-encoding polyfill](https://github.com/inexorabletash/text-encoding).

2018-04-04 15:38 UTC, yomotsu commented
@donmccurdy thanks for taking a look

Sounds the first option

> ```
> isASCII = false
> ```

is better at this moment?

I have also tried with the polyfill and it works but [the lib](https://github.com/inexorabletash/text-encoding/blob/master/lib/encoding.js) is kinda big.

2018-04-04 17:53 UTC, yomotsu commented
@donmccurdy 
I added `isASCII` option. Does it look good?

2018-04-04 18:00 UTC, donmccurdy approved these changes

2018-04-04 18:00 UTC, donmccurdy commented
Looks good to me, thanks!

2018-04-04 18:05 UTC, Mugen87 requested changes

2018-04-04 18:05 UTC, Mugen87 commented on src/loaders/LoaderUtils.js
>  		return decodeURIComponent( escape( s ) );
Maybe:
```js
return ( isASCII === true ) ? s : decodeURIComponent( escape( s ) );
```

2018-04-04 18:05 UTC, Mugen87 commented
Please update the docs, too 😇 https://threejs.org/docs/index.html#api/loaders/LoaderUtils

2018-04-04 19:04 UTC, yomotsu commented
@Mugen87 updated. but I'm not confident for the doc, since I'm not a english native speaker. I was wondering if someone could rewrite later if needed 🙇

2018-04-04 19:46 UTC, Mugen87 approved these changes

2019-05-02 16:04 UTC, Mugen87 commented
Closing in favor of #16362

2019-05-02 16:04 UTC, closed without merging