following PR #13787 removing extra commas and correction for g style …
mrdoob/three.js pull request #13796
Opened 2018-04-07 19:40 UTC by ndebeiss

…being overriden by empty style on path tag, temp correction, more to come

2018-04-07 19:43 UTC, Mugen87 requested changes

2018-04-07 19:43 UTC, Mugen87 commented on examples/js/loaders/SVGLoader.js
> +			}
Please write it like this: 
```js
if ( node.style.fill !== '' ) style.fill = node.style.fill;
```

2018-04-07 20:30 UTC, Mugen87 commented
No problem. But it's not perfect yet :wink:.

Please respect the spaces between the brackets and the `!==` operator.

2018-04-07 20:31 UTC, Mugen87 approved these changes

2018-04-08 04:35 UTC, merged

2018-04-08 04:35 UTC, mrdoob commented
Thanks!