CSS2DRenderer: add z respecting
mrdoob/three.js pull request #13959
Opened 2018-04-30 04:59 UTC by yomotsu

This PR is adding z respecting for CSS2DRenderer with similar way to IE11 support of CSS3DRenderer.

Current CSS2DRenderer does not respect depth.
Here is the problem: Label "Moon" is always front
https://jsfiddle.net/7w462nk9/
![2](https://user-images.githubusercontent.com/212837/39415371-57ebeb72-4c7d-11e8-9d79-d8f98aa0a8fc.gif)

I also added an example for CSS2DRenderer which is missing in the examples.
https://rawgit.com/yomotsu/three.js/css2d-renderer-respect-z/examples/index.html?q=css2d#css2d_label

2018-04-30 07:37 UTC, Mugen87 requested changes

2018-04-30 07:37 UTC, Mugen87 commented on examples/css2d_label.html
> +				renderer2.render( scene, camera );
Can you please rename `renderer2` to `labelRenderer`?

2018-04-30 07:37 UTC, Mugen87 commented on examples/js/renderers/CSS2DRenderer.js
> +	}
Missing comma.

2018-04-30 10:29 UTC, yomotsu commented
@Mugen87 Thanks for your review. I changed them.

2018-05-04 18:00 UTC, mrdoob commented
/ping @Mugen87

2018-05-04 18:31 UTC, Mugen87 approved these changes

2018-05-30 16:34 UTC, merged

2018-05-30 16:34 UTC, mrdoob commented
Thanks!