Fix #14013
mrdoob/three.js pull request #14182
Opened 2018-05-31 13:18 UTC by boulabiar

This is only a fix for chrome #14013

2018-05-31 14:35 UTC, Mugen87 requested changes

2018-05-31 14:35 UTC, Mugen87 commented on examples/js/controls/TrackballControls.js
> +        document.body.style.touchAction = "none";
Please use hard tabs instead of soft tabs. Besides, I would write it like this:
```js
document.body.style.touchAction = `none`; // see #14013
```

2018-06-01 10:04 UTC, Mugen87 commented
Um, something strikes me. This fix works for fullscreen applications. But what happens when the canvas is embedded in a web site surrounded by ordinary web content? Setting `document.body.style.touchAction` to `none` would affect the entire page which could be problematic. Maybe the following is more robust:
```js
if ( this.domElement instanceof HTMLElement ) {

     this.domElement.style.touchAction = 'none';

} else {

    document.body.style.touchAction = 'none';

}
```

2018-06-01 11:01 UTC, boulabiar commented
You are absolutely right. My bad why I didn't thought of this.

2018-07-31 14:51 UTC, mrdoob commented
This looks like should be a bug report for Chrome instead... 🤔

2018-07-31 15:44 UTC, boulabiar commented
I reported the bug to chrome
https://bugs.chromium.org/p/chromium/issues/detail?id=841282

But this is intentional! They want it like that.. It's their new policy and they don't want to change it.
Meanwhile, three.js is still getting this issue in that example. (everybody using chrome mobile has it, tested it on 5 phones already)

2018-08-25 22:01 UTC, mrdoob commented
So the fact that this is not an issue on with `OrbitControls` is because we're calling `event.preventDefault()` in the `touchstart` event. 

https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/OrbitControls.js#L813

Do you mind updating the PR to do that instead? Seems simpler than messing with css styles.

2018-08-26 21:58 UTC, mrdoob commented
I see... Well, for the time being I'm going to add these just to match the other controls. I'll investigate the issue more in depth next week.

2018-10-19 22:38 UTC, closed without merging

2018-10-20 09:02 UTC, boulabiar commented
this is the video of the dev branch showing the same problem.
https://www.youtube.com/watch?v=qQov0Eei_uU

I've already reported this here
https://github.com/mrdoob/three.js/pull/14622#issuecomment-410162595

Now with this commit we have a wrong fps indicator.