CurvePath: Add isLineCurve3 check
mrdoob/three.js pull request #14288
Opened 2018-06-14 16:11 UTC by git-mormot

2018-06-14 17:46 UTC, Mugen87 requested changes

2018-06-14 17:46 UTC, Mugen87 commented on src/extras/core/CurvePath.js
>  				: ( curve && curve.isLineCurve ) ? 1
Why not?
```js
: ( curve && ( curve.isLineCurve || curve.isLineCurve3 ) ) ? 1
```

2018-06-15 13:36 UTC, git-mormot commented on src/extras/core/CurvePath.js
>  				: ( curve && curve.isLineCurve ) ? 1
Oh its better. I will change it again.

2018-06-15 13:51 UTC, Mugen87 approved these changes

2018-06-15 23:46 UTC, merged

2018-06-15 23:46 UTC, mrdoob commented
Thanks!