Add sprite raycast demo
mrdoob/three.js pull request #14488
Opened 2018-07-17 07:43 UTC by 06wj

As https://github.com/mrdoob/three.js/pull/14292#issuecomment-405476140 suggested, add sprite raycast demo to the example list.

[live demo](https://rawgit.com/06wj/three.js/patch0/examples/index.html?q=sprite#webgl_raycast_sprite)

2018-07-17 09:50 UTC, Mugen87 requested changes

2018-07-17 09:50 UTC, Mugen87 commented on examples/webgl_raycast_sprite.html
> +            initRender();
I suggest you don't make all this functions (`initRender`, `initScene`...) but put the code to directly into `init()`. In this way the example is more consistent to the others.

2018-07-17 09:50 UTC, Mugen87 commented on examples/webgl_raycast_sprite.html
> +            } );
This is no good approach since you "fake" a `Vector3` object. Do this instead: `camera.lookAt( scene.position )`;

2018-07-17 09:50 UTC, Mugen87 commented on examples/webgl_raycast_sprite.html
> +            camera.position.y = 15;
`camera.position.set( 15, 15, 15 );`

2018-07-17 09:50 UTC, Mugen87 commented on examples/webgl_raycast_sprite.html
> +            controls.target = new THREE.Vector3( 0, 0, 0 );
This line is superfluous.

2018-07-17 09:55 UTC, linkenneth commented
There are some issues with raycasting after window resizing. We probably want some window resizing logic here as well.

2018-07-17 11:01 UTC, 06wj commented
@linkenneth Fixed it.

2018-07-17 11:07 UTC, Mugen87 commented on examples/webgl_raycast_sprite.html
> +        function render() {
Please rename `render()` to `animate()` and call it right after `init()` in line 34 so you have this workflow.

```js
init();
animate();
```

2018-07-17 11:18 UTC, Mugen87 approved these changes

2018-07-29 18:53 UTC, merged

2018-07-29 18:53 UTC, mrdoob commented
Thanks!