toString for Color
mrdoob/three.js pull request #14605
Opened 2018-08-01 03:12 UTC by trusktr

A standard JavaScript method.

Useful with other APIs that serialize/deserialize using `toString`.

Example based on [SkateJS](http://skatejs.netlify.com) props:

```js
export default
function createPropType(Type, override = {}) {
    return {
        attribute: { source: true },
        coerce: val => val instanceof Type ? val : new Type(val),
        default: new Type,
        deserialize: val => new Type(val),
        serialize: val => val.toString(),
        ...override,
    }
}
```

```js
import * as THREE from 'three'
import createPropType from './createPropType'

skateTHREEColorProp = createPropType(THREE.Color)
```

2018-08-01 05:04 UTC, WestLangley commented
Yet, depending on the use case, it could be
```javascript
'0x' + color.getHexString();
```

2018-08-01 08:29 UTC, Mugen87 commented
Um, but values like `0xffffff` are numbers, right? You normally don't work with them as strings. Against this backdrop, I think the PR is okay like that.

2018-08-01 08:31 UTC, Mugen87 requested changes

2018-08-01 08:31 UTC, Mugen87 commented on src/math/Color.js
> +
Please remove these trailing spaces in line 455.

2018-08-01 16:12 UTC, WestLangley commented
I'm not liking the proposed method name. I do not think it is sufficiently descriptive.

IMO, `.getHexString()` should be modified to return proper hexadecimal syntax:  `#0000ff`.

Optionally, `.getStyle()` could be renamed to `.getRGBString()`, although I understand why it was named the way it was.

The method names `.getHexString()` and `.getRGBString()` would be an improvement, IMO.

2019-06-19 13:27 UTC, Mugen87 commented
Closing. Users can still monkey path `Color` with a custom `toString()` method.

2019-06-19 13:27 UTC, closed without merging