Transform controls v2 stopPropagation patch
mrdoob/three.js pull request #14619
Opened 2018-08-02 09:14 UTC by arodic

@trusktr @but0n @brettkromkamp reported issues with new TransformControls not playing nice with OrbitControls and it appears to be due to `event.stopPropagation()` on mousedown and mousemove.

This patch brings back conditional stopPropagation as it was in previous version (only stops propagation if pointer is hovering on top of axis).

2018-08-02 09:31 UTC, but0n commented
Looks good to me, thanks!

2018-08-02 15:33 UTC, but0n requested changes

2018-08-03 09:33 UTC, but0n commented
Yeah, I've noticed it too, the editor is using `THREE.EditorControls()`.

2018-08-06 09:09 UTC, ieskudero commented
This patch fixes the issue of letting the THREE.OrbitControls() work, but if the object is dragging it shouldn't let move. Maybe it´s a better idea to put the stopPropagation() function after the checking line inside the pointerMove() function:

if ( object === undefined || axis === null || this.dragging === false || ( pointer.button !== undefined && pointer.button !== 0 ) ) return;

pointer.e.stopPropagation(); //assuming we pass the event int the pointer data structure

This way the camera doesn't move when we are dragging the object.

2018-08-08 19:45 UTC, arodic commented
> This patch fixes the issue of letting the THREE.OrbitControls() work, but if the object is dragging it shouldn't let move.

@ieskudero are you still experiencing OrbitControls moving camera while TransformControls is being dragged with this patch? Im getting correct behavior in webgl_geometry_spline_editor, misc_controls_transform and editor.

It appears to me that this somewhat depends on how your app handles multiple controls.

Personally, I think the best solution to remove `stopPropagation()` entirely and let application listen transformControl state changes and configure other controls appropriately. (OrbitControls or whatever other tool). The downside is that this approach requires additional code on application side.

Other approach (which worked OK before) is to use `stopPropagation()` to hack both controls to work simultaneously out of the box. This lets developers to simply attach both TransformControls and OrbitControls and they simply work which is great. The downside of this approach is that it is kind of a hack and might have other side-effects.

2018-08-08 19:57 UTC, arodic commented
`if ( object === undefined || axis === null || this.dragging === false || ( pointer.button !== undefined && pointer.button !== 0 ) ) return;`

`object === undefined` is redundant because this case always causes axis to be falsey.

`this.dragging === false` this makes sense, I'l add it to pointerMove as sanity check.

`pointer.button !== undefined && pointer.button !== 0` this also seems redundant since dragging will be false unless button is pressed.

2018-08-08 20:28 UTC, arodic commented
@mrdoob do you have any thoughts on this?

Personally I would remove `stopPropagation()` hack alltogether and attach mousemove listeners to document so drag works outside document borders. However, this would force developers to manually enable/disable multi-control setups in similar fashion like the editor in Viewport.js

2018-08-09 06:42 UTC, ieskudero commented
I agree that **stopPropagation()**  should be removed in order to keep the control clean (it´s dangerous to have a control stopping events), but I would set a comment or something that tells the user to make use of the **dragging** variable to know when the control is dragging.

Maybe it would be good to have a mainControl class to manage situations where there are multiple controls in the scene.

By the way, and out of topic, another feature that would be great would be the posibility of hiding gizmo's axis separately,  having boolean variables like **showPosX = false** or **showRotZ = false** to do it.

2018-08-09 07:54 UTC, arodic commented
> Maybe it would be good to have a mainControl class to manage situations where there are multiple controls in the scene.

I agree maybe it can be called `ControlManager` or something like that. I can imagine situations where you might want to have more than two controls operating simultaneously in 3D modeling tools for example. Also, I proposed this many times before, it would be useful to standardize all controls by extending a single `Control` class. I am quite interested in this topic (interactive tools and controls) so I'll probably create a separate repository just for that.

> By the way, and out of topic, another feature that would be great would be the posibility of hiding gizmo's axis separately, having boolean variables like showPosX = false or showRotZ = false to do it.

What is the intended use for this? Similar issue #11340 was closed now that axes hide automatically when facing camera. I thought the use case was to have better UX in orthographic side views for example. Your suggestion sounds like you want to prevent users from moving in particular axis regardless of camera view, right? Perhaps we can reopen #11340 and discuss it there.

2018-08-09 08:50 UTC, arodic commented
OK, so I removed the ugly `stopPropagation()` hack. This means that multi-control apps need to listen to **dragging-changed** event on TransformControls and enable/disable other controls. For example:

```javascript
transformControl.addEventListener( 'dragging-changed', function ( event ) {
    orbitControls.enabled = !event.value
} );
```

examples using TransformControls have also been updated to reflect this change. Editor (Viewport.js) is unaffected by this change.

2018-08-09 09:09 UTC, ieskudero commented
I didn't know of #11340, and I definitely would love to have axis disabled. A work project I'm working on needs to move some objects alongside X axis, restricting the other axis. I can stop the movement in some axis, but it would be great if the control showed only the axis that the object could move.

An event before showGizmo or something similar where I could change the visibility of the axis, alongside the booleans variables that I commented before should covert almost every posibility.

I think it´s a feature that many people could use. Anyway, #11340 should be the place to discuss it.

2018-08-25 21:34 UTC, mrdoob commented
@arodic could you fix the conflicts?

2018-08-26 16:49 UTC, arodic commented
@mrdoob done

2018-08-29 05:05 UTC, merged

2018-08-29 05:05 UTC, mrdoob commented
Thanks!