Edit button in docs localization bug fix #15136
mrdoob/three.js pull request #15157
Opened 2018-10-28 08:29 UTC by maru0301

\docs\index.html
edit button localization link bug fix
[https://github.com/mrdoob/three.js/issues/15136](#15136)

2018-10-28 17:06 UTC, moraxy commented
That would break the `Source` links at the bottom of the API pages (e.g. [live link](https://raw.githack.com/maru0301/three.js/dev/docs/index.html#api/en/cameras/ArrayCamera))

2018-10-29 10:40 UTC, Mugen87 commented
Correct. This PR will not solve the problem. One solution is presented in https://github.com/mrdoob/three.js/issues/15136#issuecomment-433650832. But there might be a smarter approach...

2018-10-30 01:17 UTC, maru0301 commented
It seems best to think that it is best to pass the language setting on the right page when selecting the language and receive it.
Other than that
· Extract language setting for edit button
· Do not include language setting on source link Set to URL

Is not it?
I would like to try it with any of the above

2018-10-30 09:06 UTC, Mugen87 commented
I think `page.js` needs a bit of refactoring in order so make things more nice. But I don't think it's necessary to do this now. I vote for a quick/dirty fix just to ensure the `Edit Button` works again. In the next step, it's okay to think about a different handling of the language setting.

2018-10-30 11:11 UTC, Mugen87 commented
For testing: https://raw.githack.com/maru0301/three.js/dev/docs/index.html

2018-10-30 11:12 UTC, Mugen87 commented
Your approach seems to work fine 👍

2018-10-30 11:13 UTC, maru0301 commented
Yes, thank you!

2018-10-30 11:14 UTC, Mugen87 requested changes

2018-10-30 11:14 UTC, Mugen87 commented on docs/page.js
> +	var languageReg = new RegExp( "/" + section + "/[A-z0-9\-]+/[A-z0-9\-]+/" );
Just some style feedback: Please use ' instead of ".

2018-10-30 11:14 UTC, Mugen87 commented on docs/page.js
> +	languageReg = new RegExp( "/"+section+"/[A-z0-9\-]+/" );
Please write it like so (notice the additional spaces)
```js
languageReg = new RegExp( '/' + section + '/[A-z0-9\-]+/' );
```

2018-10-30 11:29 UTC, maru0301 commented
I applied feedback.

2018-10-30 11:30 UTC, Mugen87 approved these changes

2018-10-30 11:30 UTC, Mugen87 commented
Let's see what @mrdoob thinks about the fix 😊

2018-10-30 11:31 UTC, maru0301 commented
Yes
Thank you so much today!

2018-10-30 11:55 UTC, Mugen87 commented
Funny, your name "Maru" remembers me at a certain cat 😁 

https://www.youtube.com/watch?v=hPzNl6NKAG0

2018-10-30 12:15 UTC, maru0301 commented
Hahaha,
maru is my real nickname 😊

2018-11-15 12:05 UTC, Mugen87 commented
@mrdoob Do you think this fix is appropriate? Or do we need a different approach?

2018-12-10 09:38 UTC, Mugen87 commented
Solved via #15399

@maru0301 In any event, thanks for your work ❤️

2018-12-10 09:38 UTC, closed without merging