Fire and smoke example
mrdoob/three.js pull request #15366
Opened 2018-12-04 01:24 UTC by mikepiecuch

This is my first contribution to three.js.  I think this library is amazing and I want to give back.

This is an example of fire and smoke based on the research paper:

"Real-Time Fluid Dynamics for Games" by Jos Stam
http://www.dgp.toronto.edu/people/stam/reality/Research/pdf/GDC03.pdf

2018-12-04 01:49 UTC, looeee commented
For testing: https://raw.githack.com/mikepiecuch/three.js/fire_example/examples/webgl_fire.html

2018-12-04 11:07 UTC, Mugen87 requested changes

2018-12-04 11:07 UTC, Mugen87 commented on examples/webgl_fire.html
> +				var plane = new THREE.PlaneGeometry( 20, 20 );
Please use `BufferGeometry` at all places. So in this case `PlaneBufferGeometry`.

2018-12-04 11:07 UTC, Mugen87 commented on examples/webgl_fire.html
> +				renderer.antialias = true;
This line seems redundant to me.

2018-12-04 11:07 UTC, Mugen87 commented on examples/js/Fire.js
> +	this.fieldGeometry = new THREE.PlaneGeometry( textureWidth, textureHeight );
`PlaneBufferGeometry`.

2018-12-04 11:07 UTC, Mugen87 commented on examples/js/Fire.js
> +											   textureHeight,
Some formatting issues.

2018-12-04 11:07 UTC, Mugen87 commented on examples/js/Fire.js
> +		format: THREE.RGBAFormat,
The default is already `THREE.RGBAFormat`.

2018-12-04 11:07 UTC, Mugen87 commented
A better place for `Fire.js` might be `examples/js/objects/`.

2018-12-05 11:33 UTC, Mugen87 approved these changes

2018-12-31 13:41 UTC, merged

2018-12-31 13:41 UTC, mrdoob commented
Thanks!