Support bump and ambient material techniques, added uv2 layer
mrdoob/three.js pull request #15391
Opened 2018-12-07 05:38 UTC by jbaicoianu

When we switched to the new ColladaLoader, we lost support for normal maps, lightmaps, and second uv layers.  This patch adds them back.  Compare screenshots below:

Before patch:
![image](https://user-images.githubusercontent.com/251610/49629568-f972cf00-f99e-11e8-9c12-24c0841295f8.png)

After patch:
![image](https://user-images.githubusercontent.com/251610/49629577-01327380-f99f-11e8-9406-27937359d558.png)

This was previously discussed in #10882 as well

2018-12-07 10:57 UTC, Mugen87 requested changes

2018-12-07 10:57 UTC, Mugen87 commented on examples/js/loaders/ColladaLoader.js
> +						var inputname = (set > 0 ? semantic + set : semantic);
Minot style issue:
```js
( set > 0 ? semantic + set : semantic );
```

2018-12-07 19:11 UTC, jbaicoianu commented on examples/js/loaders/ColladaLoader.js
> +						var inputname = (set > 0 ? semantic + set : semantic);
Fixed

2018-12-07 19:35 UTC, Mugen87 approved these changes

2018-12-11 00:52 UTC, merged

2018-12-11 00:52 UTC, mrdoob commented
Thanks!