Docs: zh tranlations.
mrdoob/three.js pull request #15439
Opened 2018-12-16 12:11 UTC by gogoend

Translate some untranslated page ,and fix some wrong words or expressions.

2018-12-16 17:03 UTC, Mugen87 commented
Hint: You might want to scan the zh-docs for the `TODO` string. When I'm updating the english docs, I always try to update the structure of the Chinese pages but of course without the actual translation. I normally use `TODO` as a placeholder.

2018-12-17 01:34 UTC, gogoend commented
> Hint: You might want to scan the zh-docs for the `TODO` string. When I'm updating the English docs, I always try to update the structure of the Chinese pages but of course without the actual translation. I normally use `TODO` as a placeholder.

OK,got it~

2018-12-17 02:20 UTC, gogoend commented
Besides,I found the link `https://github.com/KhronosGroup/glTF/issues/9562` at `Loading` section in manual/en/introduction/Loading-3D-models (line 100) is not available.

2018-12-17 11:54 UTC, Mugen87 commented
Oh, I think the link should be https://github.com/mrdoob/three.js/issues/9562. Can you please replace it in both versions (en, zh)?

2018-12-17 12:53 UTC, gogoend commented
> Oh, I think the link should be #9562. Can you please replace it in both versions (en, zh)?

With pleasure.

2018-12-17 13:05 UTC, Mugen87 requested changes

2018-12-17 13:05 UTC, Mugen87 commented on docs/api/en/extras/curves/EllipseCurve.html
> -		</p>
Why have you deleted this section?

2018-12-17 13:46 UTC, Mugen87 commented on docs/api/en/extras/curves/EllipseCurve.html
> -		</p>
Good catch :+1:

2018-12-17 13:46 UTC, Mugen87 approved these changes

2018-12-17 18:37 UTC, merged

2018-12-17 18:37 UTC, mrdoob commented
Thanks!