TypeScript: Added remaining material definitions.
mrdoob/three.js pull request #16163
Opened 2019-04-05 15:42 UTC by Mugen87

Title says it all^^

@Methuselah96 Do you mind verifying the PR? 😇

2019-04-05 19:00 UTC, Methuselah96 requested changes

2019-04-05 19:00 UTC, Methuselah96 commented on src/materials/MeshMatcapMaterial.d.ts
> +	map?: Texture;
The indentation looks inconsistent.

2019-04-05 19:04 UTC, Methuselah96 requested changes

2019-04-05 19:04 UTC, Methuselah96 commented on src/materials/MeshDepthMaterial.d.ts
> +	displacementMap?: Texture;
`Texture` needs to be imported.

2019-04-05 19:17 UTC, Methuselah96 requested changes

2019-04-05 19:17 UTC, Methuselah96 commented on src/materials/MeshDistanceMaterial.d.ts
> +	referencePosition?:  Vector3;
The extra space before `Vector3` should be removed.

2019-04-05 19:17 UTC, Methuselah96 commented on src/materials/MeshDistanceMaterial.d.ts
> +	referencePosition:  Vector3;
The extra space before `Vector3` should be removed.

2019-04-05 19:17 UTC, Methuselah96 commented on src/materials/MeshDistanceMaterial.d.ts
> +	referencePosition:  Vector3;
```suggestion
	referencePosition: Vector3;
```

2019-04-05 19:17 UTC, Methuselah96 commented on src/materials/MeshDistanceMaterial.d.ts
> +	referencePosition?:  Vector3;
```suggestion
	referencePosition?: Vector3;
```

2019-04-05 19:52 UTC, Mugen87 commented
Many thanks 👍 ! I've implemented your feedback.

2019-04-05 19:58 UTC, Methuselah96 approved these changes

2019-04-06 04:26 UTC, merged

2019-04-06 04:26 UTC, mrdoob commented
Thanks!