clone euler rotation order when cloning/copyng object3d
mrdoob/three.js pull request #19789
Opened 2020-07-03 21:29 UTC by luisfonsivevo

Not sure if there is a technical reason behind why the euler rotation order isn't cloned by Object3D.copy(), but hey now it is.

2020-07-03 22:03 UTC, trusktr requested changes
There should instead be a line

```js
this.rotation.copy(source.rotation)
```

that handles it.

2020-07-03 22:21 UTC, luisfonsivevo commented
If we copy the entire euler instead of only copying its order, it won't be necessary to copy the quaternion anymore. Because inside `Euler.copy()`, the onChangeCallback is called which automatically recalculates the quaternion. So really, it's only necessary to copy either the quaternion or the euler.

This (what I have currently)
```
this.position.copy( source.position );
this.rotation.order = source.rotation.order;
this.quaternion.copy( source.quaternion );
this.scale.copy( source.scale );
```

or this (a bit more concise)
```
this.position.copy( source.position );
this.rotation.copy( source.rotation );
this.scale.copy( source.scale );
```

will both get the job done.

2020-07-04 00:05 UTC, WestLangley commented
1. three.js is quaternion-based; the Euler angles are provided for user-convenience.

2. Quaternions are not unique -- and neither are Euler angles. Copying `object.rotation` will result in identical Euler angles, but possibly different quaternions.

That is why the quaternion is copied, and not the rotation.

Failing to copy `rotation.order` was an oversight.

This PR, as written, is correct.

2020-07-04 00:14 UTC, luisfonsivevo commented
When you say quaternions are not unique, do you mean that two quaternions with different xyzw values can represent the same orientation? I never knew that.

2020-07-04 02:05 UTC, merged

2020-07-04 02:05 UTC, mrdoob commented
Thanks!

2020-07-04 16:06 UTC, WestLangley commented
@luisfonsivevo Unit quaternions `q( x, y, z, w )` and `q( - x, - y, - z, - w )` represent the same orientations.