eslint: Clean up.
mrdoob/three.js pull request #20833
Opened 2020-12-05 07:14 UTC by linbingquan

**Description**

Fllowup of #20827

2020-12-05 07:23 UTC, gkjohnson commented
Looks like I forgot to push the modularize commit... thanks for the follow up!

2020-12-05 09:35 UTC, Mugen87 approved these changes

2020-12-08 09:37 UTC, Mugen87 requested changes
Without updating the modularize script, these changes will be overwritten again.

2020-12-08 09:40 UTC, Mugen87 commented
Closing in favor of #20852.

2020-12-08 09:40 UTC, closed without merging