copyTextureToTexture sourcebox, flipY from source
mrdoob/three.js pull request #21986
Opened 2021-06-14 14:39 UTC by mbredif

Related issue: #21942 

**Description**

This PR aligns the apis of copyTextureToTexture and copyTextureToTexture3D in the WebGLRenderer : 
- copyTextureToTexture was missing a source box parameter (only full images could be copied)
- a source level is added to enable copying a higher level than 0 from the source image for advanced uses.
- the parameters are reordered in both functions as `( srcTexture, dstTexture, dstPosition = undefined, srcBox = undefined, dstLevel = 0, srcLevel = 0 )` as all parameters but textures have sensible defaults (destination position at origin, full source box and levels at 0).
- usage of the previous api is detected by checking if the first argument is a texture, to reorder the parameters and print a deprecation warning.

examples/webgl_materials_texture_partialupdate.html 
- it now demonstrates copying sub parts of an input 2D texture

The box is reduced so that it points to valid pixels in both the source and destination textures. As an alternative, this code could be simplified if this burden is given to the user (big boxes will trigger webgl error).

finally, the UNPACK parameters are now taken from the source texture rather than the destination texture. It makes more sense in my use cases (otherwise I always end up at least copying flipY and unpackAlignment from the srcTexture to the dstTexture before the copy as a workaround)

2021-06-16 18:24 UTC, mrdoob commented
/cc @DavidPeicho

2021-06-16 20:34 UTC, DavidPeicho reviewed
At this point those methods are so complex than I am wondering if they shouldn't even be merged as a single one...
The only notable differences to me are:
* The depth component
* The unpacking
* The name of the function to upload the data

I think we can work a bit on simplifying the function while keeping the features added.

2021-06-16 20:34 UTC, DavidPeicho commented on src/renderers/WebGLRenderer.js
> +			return this.copyTextureToTexture( arguments[ 1 ], arguments[ 2 ], arguments[ 0 ], undefined, arguments[ 3 ] );
Why do you use `arguments` here instead of the named parameters?

2021-06-16 20:34 UTC, DavidPeicho commented on src/renderers/WebGLRenderer.js
> +		const image = srcTexture.mipmaps[ srcLevel ] || ( srcLevel == 0 ? srcTexture.image : null );
Hum, how should we differentiate base texture from mipmap 0? @mrdoob
Here what's happening is a bit weird to me

2021-06-16 20:42 UTC, DavidPeicho requested changes

2021-06-16 20:42 UTC, DavidPeicho commented on src/renderers/WebGLRenderer.js
> +		let skipPixels = srcBox ? srcBox.min.x : 0;
Not too important, but here we can initialize all variables to the default value, **and** then perform the condition once:
```srcBox !== undefined```.

2021-06-16 20:42 UTC, DavidPeicho commented on src/renderers/WebGLRenderer.js
> +		if ( skipPixels < 0 || x < 0 ) {
I think both of those conditions aren't needed and should work the same way `srcBox` is clamped to `0` when negative.
They add a lot of code for something the user should clearly not do. We can add a little disclaimer in the doc

2021-06-16 20:42 UTC, DavidPeicho commented on src/renderers/WebGLRenderer.js
> +		const width = Math.min( dstTexture.image.width - x, srcBox ? Math.min( image.width, srcBox.max.x + 1 ) - skipPixels : image.width );
If we decide to remove the above two conditions, then we also need to update that part because it will not be valid anymore

2021-06-17 17:51 UTC, mbredif reviewed
Thanks @DavidPeicho for the review. I gave your ideas a try, merging the two functions notably : https://github.com/mrdoob/three.js/compare/dev...mbredif:copyTextureToTexture_merged .
Is that what you had in mind ? @mrdoob and @Mugen87, do you prefer this second approach ?

2021-06-17 18:40 UTC, Mugen87 reviewed
When I initially added `copyTextureToTexture()`, it was important to me to cover the most basic use cases and keep the method simple. Now it is enhanced to cover more advanced use cases but that makes the implementation as well as the signature more complex. 

TBH, as long as there is no more demand for such features I would prefer to keep the method simple. And let advanced users monkey-patch the method if necessary.

2021-06-18 06:12 UTC, mbredif commented
What about this version ? https://github.com/mbredif/three.js/blob/copyTextureToTexture_merged/src/renderers/WebGLRenderer.js#L2083-L2227 . As @DavidPeicho mentioned, the 2 copy functions could be merged to factor common code. I also removed the box shrinking code to simplify the implementation.

2021-06-18 09:01 UTC, DavidPeicho commented on src/renderers/WebGLRenderer.js
> +		const image = srcTexture.mipmaps[ srcLevel ] || ( srcLevel == 0 ? srcTexture.image : null );
That makes sense actually. If you have mipmaps, level 0 should be the normal textures... But that's confusing

2021-06-18 09:04 UTC, DavidPeicho commented
I quite like the second version! Thanks!

It's indeed a bit of code, but that's the issue with abstracting a method that has so many options.

2024-06-19 13:22 UTC, closed without merging

2024-06-19 13:22 UTC, Mugen87 commented
The most important part of this PR (copying sub parts of an input 2D texture) was implemented in #28281. I would leave the other features out for now and only add them if they are frequently requested.