PMREMGenerator: Honor outputEncoding for color conversion.
mrdoob/three.js pull request #22318
Opened 2021-08-12 08:24 UTC by Mugen87

Related issue: see https://github.com/mrdoob/three.js/issues/22286#issuecomment-896792847

**Description**

`PMREMGenerator` now honors `WebGLRenderer.outputEncoding` when converting to linear color space.

2021-08-12 08:35 UTC, Mugen87 commented
`webgl_furnace_test` assumes sRGB for `Scene.background`.

https://github.com/mrdoob/three.js/blob/f4601f33b222c34dedb4b2d4d5dd554894fab251/examples/webgl_furnace_test.html#L113

That means it is now necessary to set `WebGLRenderer.outputEncoding` to `sRGBEncoding` which slightly changes its visuals.

2021-08-12 11:28 UTC, WestLangley requested changes
>That means it is now necessary to set WebGLRenderer.outputEncoding to sRGBEncoding

No, that does not follow. The furnace test can be rendered in any colorspace. I'd remove the changes to the furnace test.

I think it would be best if @gkjohnson reviews the PMREM edits in this PR.

2021-08-12 12:05 UTC, Mugen87 commented
I've edited the example since `Scene.background` is explicitly defined as a sRGB color (see comment).

2021-08-12 14:43 UTC, WestLangley commented
>I've edited the example since Scene.background is explicitly defined as a sRGB color (see comment).

I wrote the comment, and the comment is referring to the fact that `PMREMGenerator` is assuming the color is sRGB. This PR supposedly fixes that limitation of `PMREMGenerator`.

The furnace test is broken until [other issues](https://github.com/mrdoob/three.js/issues/22286#issuecomment-896503667) with `PMREMGenerator` are fixed.

2021-08-12 15:15 UTC, gkjohnson commented
The changes to PMREMGenerator look good -- I'm not sure if any other types of output encodings are ever used for the renderer but my only comment is if only SRGB and Linear are supported and other output encodings might be used by users (not sure why they would be) you might want to log a warning.

I'm not familiar enough with the furnace test or the interpretation of RGBE colors in the shaders to be much help there, though. `@elalish` might be a better one to ping when you start looking into that more.

2021-08-12 20:42 UTC, Mugen87 commented
>  I'm not sure if any other types of output encodings are ever used for the renderer

Um, I guess I would add support for `THREE.GammaEncoding`. The conversion can be done via `convertGammaToLinear()`. For all other constants, a warning should be logged.

2021-08-13 08:41 UTC, Mugen87 commented
With the last commit I've added support for `THREE.GammaEncoding`. `PMREMGenerator` also logs a warning now when color spaces other than linear, gamma and srgb are used.

2021-08-13 12:10 UTC, WestLangley commented
@Mugen87 @gkjohnson Sorry, but this PR is not correct.

`PMREMGenerator.fromScene()` was written to create a PMREM from something like `RoomEnviornment`. The current renderer's output colorspace is _irrelevant_ in that case. `envScene` background color should be _specified_ in linear space because the renderer will render the PMREM in linear space. The background color should not be converted by PMREM.

If @gkjohnson is creating a PMREM from his current scene, that would be different use case.

2021-08-13 12:55 UTC, Mugen87 commented
> The background color should not be converted by PMREM.

But in this case, any calls of `convertSRGBToLinear()` should be removed from `PMREMGenerator`, right?

2021-08-13 13:47 UTC, WestLangley commented
>But in this case, any calls of convertSRGBToLinear() should be removed from PMREMGenerator, right?

Yes.

And as I said, sRGB output encoding in `webgl_furnace_test.html` is optional, and should be noted as such. The conversion to linear (if needed) belongs at the app level.

2021-08-13 15:09 UTC, Mugen87 commented
Changed the title of the PR and updated the code.

2021-08-13 15:16 UTC, WestLangley commented on examples/webgl_furnace_test.html
> +					envScene.background = new THREE.Color( COLOR );
You need to add this:
```js
if ( renderer.outputEncoding === THREE.sRGBEncoding ) envScene.background.convertSRGBToLinear();
```

2021-08-13 15:23 UTC, Mugen87 commented on examples/webgl_furnace_test.html
> +					envScene.background = new THREE.Color( COLOR );
Done!

2021-08-13 15:29 UTC, gkjohnson commented
> If @gkjohnson is creating a PMREM from his current scene, that would be different use case.

I see what you're saying. The couple times I've used PMREMGenerator it's been to render my current scene in order to get reflections on objects in that scene. It seems it would be difficult to simply support both use cases here.

This comes back to something like #22275 and / or bookkeeping color space information on the Color class so the renderer has the relevant information to interpret the colors correctly.

2021-08-13 15:49 UTC, WestLangley approved these changes

2021-08-13 18:25 UTC, merged

2021-08-13 18:27 UTC, WestLangley commented
Merging for now so #22326 can be fixed.

2021-08-15 17:53 UTC, mrdoob commented
Thanks!