LDraw Loader: Include building step count in model (assemble multiple parts per step)
mrdoob/three.js pull request #24868
Opened 2022-10-28 16:52 UTC by sbgib

Adds building steps to the LDraw Loader.

`numBuildingSteps` and `buildingStep` properties are included in the model to count and index the `STEP` commands in the LDraw model file. This allows 'assembling' multiple parts together in one step, as you would see in an instruction booklet. The visibility of objects could be changed this way instead of with construction steps, which seem to represent each object as a separate step.

Example for _car.ldr_Packed.mpd_:

```
userData: {
   buildingStep: 0
   category: null
   constructionStep: 0
   keywords: null
   numBuildingSteps: 8
   numConstructionSteps: 57
}
```

In CAD software for editing LDraw models, '_building step_' appears to be the common name for this. Sources:
[http://www.holly-wood.it/mlcad/basic6-en.html](http://www.holly-wood.it/mlcad/basic6-en.html)
[http://www.melkert.net/LDCad/docs/basicEdit](http://www.melkert.net/LDCad/docs/basicEdit)
[https://www.leocad.org/docs/tutorial1.html](https://www.leocad.org/docs/tutorial1.html)

2022-10-29 19:22 UTC, yomboprime commented
I can review this in 3 or 4 days.

2022-11-04 10:09 UTC, yomboprime commented on examples/js/loaders/LDrawLoader.js
> +			// Sets userData.numBuildingSteps number in the root THREE.Group object based on the userdata.buildingStep number in THREE.Group objects.
We should check if ```model``` has children, just for safety.

2022-11-04 10:16 UTC, yomboprime requested changes
I think we should stay with "building" or "construction" steps, but not both (it would be confusing). I was a bit simplistic when implementing construction steps, so your approach could be better.

Please modify the loader example to use building steps and see better how they work. A live link of the example would be appreciated. After that, construction steps can be removed.

Finally, the LDrawLoader docs should be updated.

2022-11-05 18:06 UTC, sbgib commented
Thanks for reviewing! That makes sense. The changes have been made and here are some live examples:

- *Original:* [https://threejs.org/examples/?q=ldraw#webgl_loader_ldraw](https://threejs.org/examples/?q=ldraw#webgl_loader_ldraw)
- *Assemby by part:* [https://codesandbox.io/s/magical-varahamihira-oefoug](https://codesandbox.io/s/magical-varahamihira-oefoug)
- *Assembly by building step:* [https://codesandbox.io/s/optimistic-pond-d4plmg](https://codesandbox.io/s/optimistic-pond-d4plmg)

Compare the effect of the *Construction step* / *Building step* slider in each case to see the intended difference. Having the flexibility to use the steps or not would be ideal, so the *Assemby by part* example shows how the latter can be achieved even without them. This way, no functionality is lost.

It became clear that `model.traverse` is preferable to `model.children` where sub-models (*.ldr*) have also been used. So the original approach is maintained here, except that `startingBuildingStep` is reset to `false` again after pushing to `subobjects`. After some testing, it seems that's what is needed to respect the steps throughout the entire model.

`constructionSteps` are renamed to `buildingSteps` here as well, though that's not strictly necessary.

2022-11-05 19:21 UTC, yomboprime approved these changes
Thanks! Looks good.

2022-11-05 21:05 UTC, merged