Add default material technique support to glTFLoader.js
mrdoob/three.js pull request #9726
Opened 2016-09-21 08:00 UTC by richtr

The [glTF specification](https://github.com/KhronosGroup/glTF/tree/master/specification) says the following:

> The technique property is optional; if it is not supplied, and no extension is present that defines material properties, then the object will be rendered using a default material with 50% gray emissive color. See Appendix A.

In [Appendix A](https://github.com/KhronosGroup/glTF/tree/master/specification#appendix-a) of the spec the default material is also discussed.

This PR adds a default material `technique` in the case that one is not supplied.

ping @tparisi for review.

2016-09-21 08:38 UTC, richtr commented
Here's is a demo with the PR applied: https://richtr.github.io/three.js/examples/?q=gltf#webgl_loader_gltf.

There is an additional issue in the glTF rendering that is documented here https://github.com/assimp/assimp/issues/1002.

Would you have an idea what the issue is here @tparisi? It looks like the glTF loader is either not rendering the geometry correctly or the conversion tool used is not writing the geometry to the glTF file correctly but I'm unsure which code is at fault.

2016-09-21 16:06 UTC, richtr commented
It looks like assimp/assimp#1002 is now fixed.

However, we still need this PR to run assimp-converted glTFs since that conversion tool does not add its own material `technique` to exported glTF files.

2016-09-21 20:53 UTC, mrdoob commented on examples/js/loaders/gltf/glTFLoader.js
> +				else if (!material.technique) {
Can we do more specific checks? `material.technique !== undefined`

2016-09-21 20:54 UTC, mrdoob requested changes

2016-09-21 20:55 UTC, mrdoob commented
@tparisi looks good?

2016-09-22 01:00 UTC, richtr commented on examples/js/loaders/gltf/glTFLoader.js
> +				else if (!material.technique) {
If re-written this line as `else if (material.technique === undefined) {`.

2016-09-22 04:09 UTC, mrdoob commented on examples/js/loaders/gltf/glTFLoader.js
> +				else if (!material.technique) {
Yup!

2016-09-22 04:16 UTC, tparisi commented
@mrdoob looks great, let's merge it.

2016-09-22 18:35 UTC, merged

2016-09-22 18:35 UTC, mrdoob commented
Thanks guys!